import type { Asset } from "./types";

// 日本の起業家・スタートアップが使える支援アセットのキュレーション済みデータ。
//
// 募集時期(application)は変動が激しいため、確定日(deadline/opensAt)は裏取りできたものだけを設定し、
// それ以外は周期(window)で「次にいつ頃来るか」を表現しています。
// 金額・条件・締切などの最終情報は必ず各公式サイトでご確認ください。
// データの追加・修正は GitHub への Pull Request を歓迎します。

// 掲載情報の最終確認時点（UIに表示）
export const LAST_CHECKED = "2026年6月";

export const assets: Asset[] = [
  // ===================================================================
  // 無料オフィス・インキュベーション
  // ===================================================================
  {
    id: "flap",
    name: "FLAP",
    operator: "mint（旧 Apricot Ventures）",
    region: "東京（渋谷）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "おおむね2〜3ヶ月ごとに新しい期を募集",
    },
    value: "渋谷の無料オフィスを約6ヶ月＋メンタリング",
    eligibility: "創業準備中〜創業期の起業家",
    summary:
      "創業前/創業期に特化したVC mintが運営する無料オフィス支援プログラム。期ごとに選抜チームへ約6ヶ月間オフィスとコミュニティを無償提供する。",
    url: "https://mint-vc.com/",
    tags: ["渋谷", "プレシード"],
  },
  {
    id: "foundx-founders",
    name: "FoundX Founders Program",
    operator: "東京大学 産学協創推進本部",
    region: "東京（本郷）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "rolling",
      note: "随時エントリー・選考（チーム単位）",
    },
    value: "個室オフィス最大9ヶ月・無償・非エクイティ",
    eligibility: "東京大学の卒業生・研究者など関係者",
    summary:
      "東大FoundXが提供する、すでにアイデアを持つチーム向けの最大9ヶ月の無償プログラム。個室と起業家コミュニティを提供。エビデンスに基づく支援が特徴。",
    url: "https://foundx.jp/",
    tags: ["東大", "大学発"],
  },
  {
    id: "foundx-fellows",
    name: "FoundX Fellows Program",
    operator: "東京大学 産学協創推進本部",
    region: "東京（本郷）",
    assetTypes: ["community", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: { status: "rolling", note: "随時エントリー・選考" },
    value: "コワーキング席・コミュニティ・無償",
    eligibility: "東京大学関係者でアイデア探索中の個人",
    summary:
      "アイデア探索段階の東大関係者向けプログラム。コワーキングスペースとコミュニティ、リソースへのアクセスを無償で提供する。",
    url: "https://foundx.jp/",
    tags: ["東大", "アイデア探索"],
  },
  {
    id: "todai-ipc-1stround",
    name: "東大IPC 1stRound",
    nameEn: "1stRound",
    operator: "東京大学協創プラットフォーム開発（東大IPC）",
    region: "全国（連携大学）",
    assetTypes: ["grant-subsidy", "mentoring", "community"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 夏〜秋にエントリー）",
    },
    value: "最大1,000万円規模の事業化支援（非返済・非エクイティ）",
    eligibility: "東京大学を含む複数の連携大学の研究者・学生など",
    summary:
      "東大IPCが主導する、株式を取得しない事業化支援プログラム。返済不要の活動資金とハンズオン支援を提供。複数大学が連携。",
    url: "https://www.1stround.jp/",
    tags: ["大学発", "ディープテック"],
  },
  {
    id: "asac",
    name: "青山スタートアップアクセラレーションセンター（ASAC）",
    nameEn: "ASAC",
    operator: "東京都 / 運営事業者",
    region: "東京",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年複数期で募集（1期 約5ヶ月）",
    },
    value: "無料のアクセラ・プログラム＋メンタリング",
    eligibility: "成長志向のスタートアップ",
    summary:
      "東京都の創業・成長支援拠点。約5ヶ月のアクセラレーションプログラムをメンタリング付きで無償提供。デモデイあり。",
    url: "https://asac.tokyo/",
    tags: ["東京都", "公的支援"],
  },
  {
    id: "tokyo-sogyo-station",
    name: "TOKYO創業ステーション",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["mentoring", "community", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: { status: "rolling", note: "通年（相談は予約制）" },
    value: "無料の事業相談・セミナー・助成金情報",
    eligibility: "都内で創業を目指す個人・事業者",
    summary:
      "担任制プランコンサルタントによる無料の創業相談、仮説検証支援、事業計画ブラッシュアップを提供。創業助成金などへの導線も。",
    url: "https://startup-station.jp/",
    tags: ["東京都", "創業相談"],
  },
  {
    id: "startup-hub-tokyo",
    name: "Startup Hub Tokyo",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["community", "mentoring", "free-office"],
    stages: ["idea", "seed"],
    equity: "none",
    application: { status: "rolling", note: "通年（会員登録は無料）" },
    value: "無料の交流スペース・相談・イベント",
    eligibility: "起業に関心のある個人・初期起業家",
    summary:
      "起業を志す人のための無料拠点。コンシェルジュ相談、先輩起業家とのネットワーキング、各種イベントを無償で提供する。",
    url: "https://startup-station.jp/m/startuphubtokyo/",
    tags: ["東京都", "コミュニティ"],
  },
  {
    id: "shibuya-qws",
    name: "SHIBUYA QWS",
    nameEn: "QWS",
    operator: "渋谷スクランブルスクエア",
    region: "東京（渋谷）",
    assetTypes: ["community", "free-office", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "四半期ごとにプロジェクト会員を募集",
    },
    value: "会員制の共創施設・プロジェクト支援",
    eligibility: "問いを起点に活動する個人・チーム",
    summary:
      "渋谷スクランブルスクエア内の共創施設。プロジェクト会員制度を通じて活動拠点・コミュニティ・メンタリング・発信機会を提供する。",
    url: "https://shibuya-qws.com/",
    tags: ["渋谷", "共創"],
  },
  {
    id: "fukuoka-growth-next",
    name: "Fukuoka Growth Next（FGN）",
    nameEn: "FGN",
    operator: "福岡市 ほか",
    region: "福岡",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "入居・会員は随時審査" },
    value: "官民共働の拠点・低コストの入居・支援",
    eligibility: "福岡を拠点とするスタートアップ",
    summary:
      "旧大名小学校を活用した福岡市の官民共働スタートアップ支援施設。低コストの入居、メンタリング、コミュニティ、イベントを提供する。",
    url: "https://growth-next.com/",
    tags: ["福岡", "地方拠点"],
  },
  {
    id: "osaka-innovation-hub",
    name: "Osaka Innovation Hub（OIH）",
    nameEn: "OIH",
    operator: "大阪市 / 大阪産業局",
    region: "大阪",
    assetTypes: ["community", "mentoring", "overseas"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "通年（イベント・プログラムは随時）",
    },
    value: "無料の交流拠点・ピッチ・海外連携",
    eligibility: "起業家・イノベーター（誰でも）",
    summary:
      "大阪市が運営するイノベーション創出拠点。グランフロント大阪を拠点に、年間多数のイベント、メンタリング、海外アクセラ連携などを提供。",
    url: "https://www.innovation-osaka.jp/",
    tags: ["大阪", "地方拠点"],
  },
  {
    id: "yoxo-yokohama",
    name: "YOXO（横浜スタートアップ支援）",
    nameEn: "YOXO",
    operator: "横浜市 / 横浜未来機構",
    region: "神奈川（横浜）",
    assetTypes: ["accelerator", "community", "free-office"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "アクセラは年次公募（YOXO ACCELERATOR）",
    },
    value: "無料アクセラ・交流拠点（YOXO BOX）",
    eligibility: "横浜での成長を目指すスタートアップ",
    summary:
      "横浜市のスタートアップ成長支援ブランド。交流拠点YOXO BOXや、専門家伴走型のYOXO ACCELERATORなどを通じて事業成長を支援する。",
    url: "https://yoxo-yokohama.com/",
    tags: ["横浜", "地方拠点"],
  },
  {
    id: "station-ai",
    name: "STATION Ai",
    operator: "STATION Ai株式会社（愛知県 ほか）",
    region: "愛知（名古屋）",
    assetTypes: ["free-office", "community", "mentoring", "accelerator"],
    stages: ["idea", "seed", "early", "growth"],
    equity: "none",
    application: { status: "rolling", note: "会員・入居は随時審査" },
    value: "日本最大級のスタートアップ支援拠点・会員制",
    eligibility: "スタートアップ・起業家・パートナー企業",
    summary:
      "2024年開業の国内最大級のオープンイノベーション拠点。会員制のコワーキングに加え、メンタリング、アクセラレーションプログラム、大企業・投資家とのマッチングを提供する。",
    url: "https://www.stationai.co.jp/",
    tags: ["名古屋", "地方拠点"],
  },
  {
    id: "tokyo-innovation-base",
    name: "Tokyo Innovation Base（TIB）",
    nameEn: "TIB",
    operator: "東京都",
    region: "東京（丸の内）",
    assetTypes: ["community", "mentoring", "overseas"],
    stages: ["idea", "seed", "early", "growth"],
    equity: "none",
    application: { status: "rolling", note: "通年（イベント・利用は随時）" },
    value: "都のスタートアップ戦略拠点・無料の交流／プログラム",
    eligibility: "起業家・スタートアップ関係者（誰でも）",
    summary:
      "東京都がGlobal Startup Campus構想の中核として設けた拠点。国内外の起業家・投資家・大企業が集い、イベントやプログラム、グローバル連携の機会を提供する。",
    url: "https://tib.metro.tokyo.lg.jp/",
    tags: ["東京都", "公的支援"],
  },
  {
    id: "cic-tokyo",
    name: "CIC Tokyo",
    operator: "Cambridge Innovation Center",
    region: "東京（虎ノ門）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: { status: "rolling", note: "入居・会員は随時" },
    value: "大規模なイノベーション拠点・グローバルネットワーク",
    eligibility: "スタートアップ・成長企業・支援機関",
    summary:
      "ボストン発のイノベーションセンターの日本拠点。虎ノ門ヒルズに国内最大級のフレキシブルオフィスを構え、コミュニティイベントや投資家・専門家ネットワークへのアクセスを提供する。",
    url: "https://jp.cic.com/",
    tags: ["虎ノ門", "グローバル"],
  },
  {
    id: "100banch",
    name: "100BANCH",
    operator: "パナソニック ほか",
    region: "東京（渋谷）",
    assetTypes: ["free-office", "community", "mentoring", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "GARAGEプログラムを毎月選考・採択",
    },
    value: "活動スペース・活動資金・メンター（無償）",
    eligibility: "35歳未満を中心とした若い世代のプロジェクト",
    summary:
      "パナソニックが運営する次世代の実験区。採択された若者のプロジェクトに、活動拠点・活動資金・各分野のメンターを提供し、アイデアの社会実装を後押しする。",
    url: "https://100banch.com/",
    tags: ["渋谷", "若手"],
  },
  {
    id: "intilaq",
    name: "INTILAQ 東北イノベーションセンター",
    nameEn: "INTILAQ",
    operator: "公益財団法人 東日本大震災復興支援財団 ほか",
    region: "宮城（仙台）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "会員・利用は随時" },
    value: "東北の起業家拠点・コワーキング・伴走支援",
    eligibility: "東北で挑戦する起業家・スタートアップ",
    summary:
      "仙台を拠点に東北の起業を支援するインキュベーション施設。コワーキングスペース、起業相談、メンタリング、各種イベントを通じて地域の挑戦者を後押しする。",
    url: "https://www.intilaq.jp/",
    tags: ["仙台", "地方拠点"],
  },

  // ===================================================================
  // 人材発掘・育成（タレントプログラム）
  // ===================================================================
  {
    id: "mitou-it",
    name: "未踏IT人材発掘・育成事業",
    nameEn: "MITOU",
    operator: "情報処理推進機構（IPA）",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年11月エントリー開始〜翌3月締切",
      note: "2026年度は2026/3/12で公募終了。次は2026年度後半に告知見込み",
    },
    value: "開発資金の支援＋トップエンジニアによるPM指導",
    eligibility: "25歳未満などの突出したIT人材（個人/チーム）",
    summary:
      "経産省所管IPAによる、突出したIT人材を発掘・育成する事業。採択者に開発資金とプロジェクトマネージャーによる指導を提供。OB/OGに著名起業家多数。",
    url: "https://www.ipa.go.jp/jinzai/mitou/it/index.html",
    tags: ["IPA", "登竜門"],
  },
  {
    id: "mitou-advanced",
    name: "未踏アドバンスト事業",
    operator: "情報処理推進機構（IPA）",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "上期・下期の年2回（おおむね12〜3月にエントリー）",
    },
    value: "事業化に向けた費用支援＋伴走",
    eligibility: "技術シーズの事業化を目指す個人・チーム（年齢上限なし）",
    summary:
      "未踏事業の中でも事業化志向に特化したトラック。技術的成果のビジネス化を、費用支援とビジネスメンタリングで後押しする。",
    url: "https://www.ipa.go.jp/jinzai/mitou/advanced/index.html",
    tags: ["IPA", "事業化"],
  },
  {
    id: "mitou-junior",
    name: "未踏ジュニア",
    operator: "一般社団法人 未踏",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年春（おおむね3〜4月）に公募",
    },
    value: "支援金＋メンタリング",
    eligibility: "17歳以下のクリエイター",
    summary:
      "17歳以下の若手クリエイターを対象にした未踏。突出したアイデアと技術力を持つ小中高生に、開発資金とメンターを提供する。",
    url: "https://jr.mitou.org/",
    tags: ["U17", "若手"],
  },
  {
    id: "masason-foundation",
    name: "孫正義育英財団",
    operator: "公益財団法人 孫正義育英財団",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "community"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年募集（時期は年により変動）",
    },
    value: "支援金・施設（Infinity）・ネットワーク",
    eligibility: "高い志と異能を持つ若者（25歳以下目安）",
    summary:
      "高い志を持つ若者を支援する財団。財団生には活動支援や拠点（Infinity）、人的ネットワークなどを提供する。",
    url: "https://masason-foundation.org/",
    tags: ["若手", "異能"],
  },
  {
    id: "tokyo-startup-gateway",
    name: "TOKYO STARTUP GATEWAY（TSG）",
    nameEn: "TSG",
    operator: "東京都 / NPO ETIC.",
    region: "東京",
    assetTypes: ["talent-program", "mentoring", "community"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年 初夏〜夏に公募（ビジネスコンテスト型）",
    },
    value: "無料の起業家育成プログラム＋賞金・伴走",
    eligibility: "都内在住・在勤などの起業を志す個人",
    summary:
      "東京都の起業家発掘・育成プログラム。400字の応募から始まり、半年間のメンタリングを経て事業化を目指す登竜門型コンテスト。参加無料。",
    url: "https://tokyo-startup.jp/",
    tags: ["東京都", "ビジコン"],
  },
  {
    id: "shido-next-innovator",
    name: "始動 Next Innovator",
    operator: "経済産業省 / JETRO",
    region: "全国 → 海外",
    assetTypes: ["talent-program", "mentoring", "overseas", "community"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 初夏〜夏にエントリー）",
    },
    value: "国内研修＋選抜者のシリコンバレー派遣",
    eligibility: "新規事業に挑む起業家・企業内人材など",
    summary:
      "経産省主導のイノベーター育成プログラム。数ヶ月の国内研修プログラムを経て、選抜された参加者がシリコンバレーでの現地研修に派遣される。OB/OGコミュニティも強い。",
    url: "https://sido.jp/",
    tags: ["経産省", "シリコンバレー"],
  },

  // ===================================================================
  // クラウド・SaaS クレジット
  // ===================================================================
  {
    id: "aws-activate",
    name: "AWS Activate",
    operator: "Amazon Web Services",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（条件を満たせば随時申請）" },
    value: "最大 $100,000 のAWSクレジット",
    eligibility: "対象VC/アクセラ等の紹介、または自己応募枠",
    summary:
      "スタートアップ向けにAWS利用クレジット・技術サポート・トレーニングを提供。成長ステージに応じて最大10万ドル相当のクレジットが付与される。",
    url: "https://aws.amazon.com/jp/startups/",
    tags: ["インフラ", "クレジット"],
  },
  {
    id: "ms-startups",
    name: "Microsoft for Startups Founders Hub",
    operator: "Microsoft",
    region: "全国",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（オンラインで随時申請）" },
    value: "最大 $150,000 相当のAzure等クレジット＋OpenAI等の特典",
    eligibility: "ほぼ全ての創業初期スタートアップ（VC不要枠あり）",
    summary:
      "Azureクレジット、開発ツール、OpenAI APIアクセス、メンタリング等をまとめて提供。VCの紹介なしでも申請可能な枠がある。",
    url: "https://www.microsoft.com/startups",
    tags: ["インフラ", "AI"],
  },
  {
    id: "google-cloud-startups",
    name: "Google for Startups Cloud Program",
    operator: "Google Cloud",
    region: "全国",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申請）" },
    value: "最大 $200,000（AI特化枠は更に上限あり）のGCPクレジット",
    eligibility: "創業10年以内・一定の資金調達状況などの条件",
    summary:
      "Google Cloud利用クレジットに加え、技術サポート・トレーニング・スタートアップ専任チームによる支援を提供。AIスタートアップ向けの上乗せ枠もある。",
    url: "https://cloud.google.com/startup",
    tags: ["インフラ", "AI"],
  },
  {
    id: "nvidia-inception",
    name: "NVIDIA Inception",
    operator: "NVIDIA",
    region: "全国",
    assetTypes: ["cloud-credit", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申請・無料）" },
    value: "ハード/ソフト割引・技術支援・VCネットワーク",
    eligibility: "AI・データサイエンス系スタートアップ",
    summary:
      "AI系スタートアップ向けの無料メンバーシッププログラム。製品割引、技術トレーニング、クラウドクレジット、投資家紹介などを提供。",
    url: "https://www.nvidia.com/en-us/startups/",
    tags: ["AI", "GPU"],
  },
  {
    id: "notion-startups",
    name: "Notion for Startups",
    operator: "Notion",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（パートナー経由で申請）" },
    value: "Notion Plus + AI の無料クレジット",
    eligibility: "提携アクセラ/VC等のパートナーに所属",
    summary:
      "対象スタートアップにNotionの有料プラン＋AIを一定期間無料提供。多くのアクセラレーターやVCがパートナーになっている。",
    url: "https://www.notion.com/startups",
    tags: ["SaaS", "生産性"],
  },
  {
    id: "hubspot-startups",
    name: "HubSpot for Startups",
    operator: "HubSpot",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（パートナー経由で申請）" },
    value: "初年度最大90%割引などの段階的ディスカウント",
    eligibility: "提携VC/アクセラ等のネットワークに所属",
    summary:
      "CRM・マーケ・セールスツールを大幅割引で提供。提携パートナー経由で申請でき、初年度に高い割引率が適用される。",
    url: "https://www.hubspot.com/startups",
    tags: ["SaaS", "CRM"],
  },
  {
    id: "cloudflare-startups",
    name: "Cloudflare for Startups",
    operator: "Cloudflare",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（提携パートナー経由）" },
    value: "Cloudflare各種プランのクレジット",
    eligibility: "提携VC/アクセラ等のパートナーに所属",
    summary:
      "CDN・セキュリティ・エッジ実行環境などCloudflare製品のクレジットを提供。提携パートナーのスタートアップが対象。",
    url: "https://www.cloudflare.com/forstartups/",
    tags: ["インフラ", "エッジ"],
  },
  {
    id: "mongodb-startups",
    name: "MongoDB for Startups",
    operator: "MongoDB",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（オンライン申請）" },
    value: "Atlasクレジット＋技術アドバイザー支援",
    eligibility: "創業初期のスタートアップ",
    summary:
      "マネージドDB「Atlas」の利用クレジットに加え、技術アドバイザーやパートナー特典を提供する。",
    url: "https://www.mongodb.com/startups",
    tags: ["インフラ", "DB"],
  },
  {
    id: "github-startups",
    name: "GitHub for Startups",
    operator: "GitHub",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（提携パートナー経由）" },
    value: "GitHub Enterprise 等の無料/割引提供",
    eligibility: "提携アクセラ/VC等のパートナーに所属する初期スタートアップ",
    summary:
      "対象スタートアップにGitHub Enterpriseなどを一定期間無料または割引で提供。開発インフラの基盤を初期コストを抑えて整えられる。",
    url: "https://github.com/enterprise/startups",
    tags: ["開発", "クレジット"],
  },
  {
    id: "datadog-startups",
    name: "Datadog for Startups",
    operator: "Datadog",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（提携パートナー経由）" },
    value: "監視・可観測性SaaSのクレジット＋サポート",
    eligibility: "提携VC/アクセラ等のネットワークに所属",
    summary:
      "監視・オブザーバビリティSaaS「Datadog」の利用クレジットとオンボーディング支援を提供。本番運用の可観測性を初期から導入できる。",
    url: "https://www.datadoghq.com/partner/datadog-for-startups/",
    tags: ["インフラ", "監視"],
  },

  // ===================================================================
  // アクセラレーター（民間・コーポレート）
  // ===================================================================
  {
    id: "onlab",
    name: "Open Network Lab（Onlab）",
    nameEn: "Onlab",
    operator: "デジタルガレージ",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "Seed Accelerator は年複数回のバッチ",
    },
    value: "出資＋約3〜4ヶ月の集中支援＋デモデイ",
    eligibility: "シード期のスタートアップ",
    summary:
      "日本の草分け的シードアクセラレーター。少額出資と引き換えに集中メンタリングを行い、デモデイで投資家へ繋ぐ。",
    url: "https://onlab.jp/",
    tags: ["シード", "出資あり"],
  },
  {
    id: "incubate-camp",
    name: "Incubate Camp",
    operator: "インキュベイトファンド",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "毎年開催（おおむね夏〜秋）",
    },
    value: "トップVCとの合宿型メンタリング＋投資機会",
    eligibility: "起業直後〜シードの起業家",
    summary:
      "現役VCとペアを組む合宿型アクセラレーション。短期集中で事業をブラッシュアップし、出資につながることも多い。",
    url: "https://incubatefund.com/",
    tags: ["合宿", "VC伴走"],
  },
  {
    id: "01booster",
    name: "01Booster Accelerator",
    nameEn: "01Booster",
    operator: "ゼロワンブースター",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "プログラム/テーマごとに公募",
    },
    value: "大企業連携の事業共創・メンタリング",
    eligibility: "成長志向のスタートアップ・新規事業家",
    summary:
      "国内最大級のアクセラレーター運営会社。大企業や自治体と連携した数多くのアクセラレーションプログラムを通じ、事業共創とメンタリングを提供する。",
    url: "https://01booster.co.jp/",
    tags: ["オープンイノベーション", "事業共創"],
  },
  {
    id: "samurai-incubate",
    name: "Samurai Incubate",
    operator: "サムライインキュベート",
    region: "全国",
    assetTypes: ["equity-investment", "accelerator", "mentoring"],
    stages: ["seed"],
    equity: "required",
    application: { status: "rolling", note: "随時、投資・支援を検討" },
    value: "シード出資＋ハンズオン支援",
    eligibility: "シード期スタートアップ",
    summary:
      "シード期に特化した投資・育成会社。出資とともに採用・事業開発などのハンズオン支援を行い、大企業連携プログラムも運営する。",
    url: "https://www.samurai-incubate.asia/",
    tags: ["シード", "出資あり"],
  },
  {
    id: "antler-japan",
    name: "Antler Japan",
    operator: "Antler",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "community"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "年複数回のコーホート（共同創業者探索から）",
    },
    value: "共同創業者マッチング＋初期出資",
    eligibility: "起業を志す個人（チーム未結成でも可）",
    summary:
      "グローバル展開する「ゼロからの起業」支援プラットフォーム。共同創業者探索のコーホートから始まり、有望チームへ初期出資を行う。",
    url: "https://www.antler.co/location/japan",
    tags: ["共同創業", "グローバル"],
  },
  {
    id: "deepcore",
    name: "DEEPCORE（KERNEL）",
    operator: "ディープコア",
    region: "全国",
    assetTypes: ["equity-investment", "community", "free-office"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "rolling",
      note: "随時、投資・インキュベーションを検討",
    },
    value: "AI特化の出資＋コミュニティKERNEL＋GPU環境",
    eligibility: "AI領域のスタートアップ・研究者",
    summary:
      "AIに特化したインキュベーター。出資に加え、コミュニティ「KERNEL」やGPU計算環境、研究者ネットワークへのアクセスを提供する。",
    url: "https://deepcore.jp/",
    tags: ["AI", "出資あり"],
  },
  {
    id: "beyond-next-brave",
    name: "Beyond Next Ventures「BRAVE」",
    nameEn: "BRAVE",
    operator: "Beyond Next Ventures",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "equity-investment"],
    stages: ["idea", "seed"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "毎年シーズン開催（アクセラレーション公募）",
    },
    value: "アカデミア発の事業化伴走＋投資機会",
    eligibility: "研究シーズを持つ研究者・起業家",
    summary:
      "技術系・アカデミア発スタートアップに特化したアクセラレーター。研究シーズの事業化を、メンタリングと投資検討を通じて支援する。",
    url: "https://beyondnextventures.com/",
    tags: ["ディープテック", "アカデミア"],
  },
  {
    id: "plugandplay-japan",
    name: "Plug and Play Japan",
    operator: "Plug and Play Japan",
    region: "全国",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "テーマ別バッチ（年2回前後）",
    },
    value: "大企業との事業共創・非エクイティのアクセラ",
    eligibility: "各業界テーマに合致するスタートアップ",
    summary:
      "シリコンバレー発のアクセラ／イノベーションプラットフォーム。テーマ別バッチで大企業とのマッチングやPoC機会を非エクイティで提供。",
    url: "https://japan.plugandplaytechcenter.com/",
    tags: ["オープンイノベーション", "大企業連携"],
  },
  {
    id: "google-accelerator",
    name: "Google for Startups Accelerator",
    operator: "Google",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "cloud-credit"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "テーマ別バッチで随時公募",
    },
    value: "非エクイティの集中メンタリング＋Google技術支援",
    eligibility: "成長期のテック系スタートアップ",
    summary:
      "Googleが運営する非エクイティのアクセラレーター。Googleのエンジニア・メンターによる技術／事業支援を数ヶ月間提供する。",
    url: "https://startup.google.com/programs/accelerator/",
    tags: ["非エクイティ", "テック"],
  },
  {
    id: "kddi-mugen-labo",
    name: "KDDI ∞ Labo（ムゲンラボ）",
    operator: "KDDI",
    region: "全国",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "プログラム期ごとに募集",
    },
    value: "大企業連携・メンタリング・事業共創",
    eligibility: "成長志向のスタートアップ",
    summary:
      "KDDIが運営する老舗インキュベーションプログラム。パートナー大企業との連携やメンタリングを通じて事業成長を支援する。",
    url: "https://mugenlabo.kddi.com/",
    tags: ["大企業連携", "コーポレート"],
  },
  {
    id: "tribus",
    name: "TRIBUS",
    operator: "リコー",
    region: "全国",
    assetTypes: ["accelerator", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 夏頃）",
    },
    value: "リコーのアセット活用・社内外共創",
    eligibility: "社外スタートアップ＋社内起業家",
    summary:
      "リコーが運営する、社内外の起業家が混じり合うアクセラレータープログラム。リコーの技術・販路・顧客基盤を活かした共創を支援。",
    url: "https://tribus.ricoh/",
    tags: ["コーポレート", "共創"],
  },
  {
    id: "sony-ssap",
    name: "Sony Startup Acceleration Program（SSAP）",
    nameEn: "SSAP",
    operator: "ソニーグループ",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["idea", "seed", "early"],
    equity: "optional",
    application: { status: "rolling", note: "随時、各支援メニューを提供" },
    value: "ソニーの事業創出メソッドによる伴走支援",
    eligibility: "新規事業を立ち上げる起業家・企業",
    summary:
      "ソニー社内の新規事業創出ノウハウを外部に開放した事業支援プログラム。事業アイデアの検証から立ち上げまで、専門人材による伴走やプロトタイピング支援を提供する。",
    url: "https://sony-startup-acceleration-program.com/",
    tags: ["コーポレート", "事業創出"],
  },
  {
    id: "creww-growth",
    name: "Creww Growth",
    nameEn: "Creww",
    operator: "Creww株式会社",
    region: "全国",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "大企業・自治体のプログラムごとに随時公募",
    },
    value: "大企業・自治体との事業共創プログラム多数",
    eligibility: "オープンイノベーションに挑むスタートアップ",
    summary:
      "国内最大級のオープンイノベーションプラットフォーム。多数の大企業・自治体が募集する協業プログラムにスタートアップが応募し、実証や事業共創の機会を得られる。",
    url: "https://creww.me/",
    tags: ["オープンイノベーション", "事業共創"],
  },

  // ===================================================================
  // ピッチ・登壇機会
  // ===================================================================
  {
    id: "ivs-launchpad",
    name: "IVS LAUNCHPAD",
    operator: "IVS",
    region: "全国",
    assetTypes: ["community", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年（IVS開催に合わせて公募）",
    },
    value: "国内最大級のピッチ登壇・露出機会",
    eligibility: "選考を通過したスタートアップ",
    summary:
      "国内有数のスタートアップカンファレンスIVSのピッチコンテスト。登壇により投資家・事業会社への露出と認知獲得の機会を得られる。",
    url: "https://www.ivs.events/",
    tags: ["ピッチ", "露出"],
  },
  {
    id: "icc-catapult",
    name: "ICC スタートアップ・カタパルト",
    operator: "ICCパートナーズ",
    region: "全国",
    assetTypes: ["community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年2回（ICCサミットに合わせて公募）",
    },
    value: "経営者コミュニティでのピッチ登壇機会",
    eligibility: "選考を通過したスタートアップ",
    summary:
      "ICCサミットで開催される登壇型ピッチ。質の高い経営者コミュニティの前でのプレゼン機会と、強いネットワークへのアクセスを提供する。",
    url: "https://www.industry-co-creation.com/",
    tags: ["ピッチ", "コミュニティ"],
  },
  {
    id: "tech-planter",
    name: "TECH PLANTER",
    operator: "リバネス",
    region: "全国",
    assetTypes: ["community", "mentoring", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年シーズン開催（分野別の研究シーズコンテスト）",
    },
    value: "研究シーズの事業化伴走＋パートナー連携",
    eligibility: "研究者・ディープテック起業家",
    summary:
      "リバネスが運営する研究シーズの事業化プラットフォーム。分野別コンテストと伴走支援を通じて、ディープテックの種を事業へと育てる。",
    url: "https://techplanter.com/",
    tags: ["ディープテック", "研究シーズ"],
  },
  {
    id: "bdash-camp",
    name: "B Dash Camp（Pitch Arena）",
    operator: "B Dash Ventures",
    region: "全国",
    assetTypes: ["community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年2回（春・秋のカンファレンスに合わせて公募）",
    },
    value: "招待制カンファレンスでのピッチ登壇・露出",
    eligibility: "選考を通過したスタートアップ",
    summary:
      "国内有数の招待制スタートアップカンファレンス。ピッチコンテスト「Pitch Arena」での登壇により、第一線の起業家・投資家との接点と高い露出機会を得られる。",
    url: "https://bdashcamp.com/",
    tags: ["ピッチ", "露出"],
  },

  // ===================================================================
  // 公的・グローバル展開
  // ===================================================================
  {
    id: "j-startup",
    name: "J-Startup",
    operator: "経済産業省",
    region: "全国",
    assetTypes: ["community", "overseas", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "closed",
      note: "一般公募ではなく推薦に基づく選定（不定期）",
    },
    value: "官民の集中支援・海外展開・広報露出",
    eligibility: "推薦により選定された有望スタートアップ",
    summary:
      "経産省主導で有望スタートアップを選定し、官民で集中支援する制度。海外展開支援、規制対応、大企業・自治体連携などの機会を提供。",
    url: "https://www.j-startup.go.jp/",
    tags: ["経産省", "認定"],
  },
  {
    id: "j-starx",
    name: "J-StarX",
    operator: "経済産業省",
    region: "全国 → 海外",
    assetTypes: ["overseas", "talent-program", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "コース別に随時公募（年間を通じて多数）",
    },
    value: "海外派遣・グローバル起業家育成プログラム",
    eligibility: "起業家・起業を志す学生・企業内人材など",
    summary:
      "起業家等をシリコンバレー等へ派遣する経産省の海外派遣・育成プログラム。コースが多数あり対象や段階に応じて選べる。",
    url: "https://j-starx.jp/",
    tags: ["経産省", "海外派遣"],
  },
  {
    id: "jetro-gsap",
    name: "グローバル・スタートアップ・アクセラレーションプログラム（GSAP）",
    nameEn: "JETRO GSAP",
    operator: "日本貿易振興機構（JETRO）",
    region: "全国 → 海外",
    assetTypes: ["overseas", "accelerator", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 春〜初夏）",
    },
    value: "世界トップアクセラによるエクイティフリー支援",
    eligibility: "海外展開を目指すスタートアップ",
    summary:
      "JETROが内閣府等と連携し、世界トップレベルのアクセラレーターによるエクイティフリー型の海外展開支援を提供する。",
    url: "https://www.jetro.go.jp/services/gsap.html",
    tags: ["JETRO", "エクイティフリー"],
  },
  {
    id: "japan-innovation-campus",
    name: "Japan Innovation Campus",
    operator: "経済産業省 / JETRO",
    region: "米国（シリコンバレー）",
    assetTypes: ["overseas", "community"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "rolling",
      note: "利用・入居は審査制（随時）",
    },
    value: "シリコンバレー拠点の活動スペース・現地ネットワーク",
    eligibility: "米国展開を狙うスタートアップ・支援機関",
    summary:
      "米国・シリコンバレーに設けられた日本のスタートアップ支援拠点。現地での活動スペースやネットワーキングの機会を提供する。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["シリコンバレー", "海外拠点"],
  },
  {
    id: "x-hub-tokyo",
    name: "X-HUB TOKYO",
    operator: "東京都",
    region: "東京 → 海外",
    assetTypes: ["overseas", "accelerator", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年コース別に公募（OUTBOUND/INBOUND）",
    },
    value: "海外進出に向けた無償の伴走プログラム",
    eligibility: "海外展開を目指す都内のスタートアップ",
    summary:
      "東京都が運営するグローバル展開支援プログラム。海外市場調査やメンタリング、現地アクセラとの連携を通じ、スタートアップの海外進出（OUTBOUND）と海外企業の誘致（INBOUND）を支援する。",
    url: "https://x-hub.tokyo/",
    tags: ["東京都", "海外展開"],
  },
  {
    id: "500-global-japan",
    name: "500 Global（日本）",
    nameEn: "500 Global",
    operator: "500 Global",
    region: "全国 → 海外",
    assetTypes: ["accelerator", "equity-investment", "overseas", "mentoring"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "recurring",
      window: "プログラム/ファンドごとに随時検討・公募",
    },
    value: "グローバルアクセラ＋シード出資＋海外ネットワーク",
    eligibility: "グローバル展開を志向するスタートアップ",
    summary:
      "世界各国で投資・アクセラレーションを展開するグローバルVC。日本でも出資やプログラムを通じて、シード期スタートアップの成長とグローバル展開を支援する。",
    url: "https://500.co/",
    tags: ["グローバル", "出資あり"],
  },

  // ===================================================================
  // 補助金・助成金・公的資金
  // ===================================================================
  {
    id: "nedo-nep",
    name: "NEDO Entrepreneurs Program（NEP）",
    nameEn: "NEP",
    operator: "新エネルギー・産業技術総合開発機構（NEDO）",
    region: "全国",
    assetTypes: ["grant-subsidy", "mentoring", "talent-program"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年1〜4月頃にコース別公募",
      note: "2026年度は開拓2/24・躍進4/17で締切（終了）。次年度は2027年初頭見込み",
    },
    value: "ディープテックの起業候補人材向け活動費＋伴走支援",
    eligibility: "技術シーズを持つ、または技術活用アイデアを持つ起業家候補",
    summary:
      "NEDOが実施する創業前〜創業初期の起業家候補人材育成プログラム。開拓コースや躍進コースを通じて、技術シーズの事業化に向けた活動費と専門家の伴走支援を提供する。",
    url: "https://nep.nedo.go.jp/",
    tags: ["ディープテック", "研究開発", "起業前"],
  },
  {
    id: "nedo-dtsu",
    name: "NEDO ディープテック・スタートアップ支援事業（DTSU）",
    nameEn: "DTSU",
    operator: "新エネルギー・産業技術総合開発機構（NEDO）",
    region: "全国",
    assetTypes: ["grant-subsidy", "funding", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "STS/PCA/DMPなどフェーズ別に公募",
      note: "第9回公募は2025/12/3で終了。次回公募はNEDO公募情報で確認",
    },
    value: "STS最大3〜5億円、PCA最大5〜10億円規模などの研究開発助成",
    eligibility: "研究開発型スタートアップ（設立年数・VC等からの資金調達要件あり）",
    summary:
      "ディープテック領域の研究開発型スタートアップを、実用化研究開発（STS/PCA）から量産化実証（DMP）まで段階的に支援する大型助成事業。技術実証・試作・量産準備の資金ギャップを埋める重要制度。",
    url: "https://www.nedo.go.jp/activities/ZZJP_100250.html",
    tags: ["ディープテック", "研究開発", "大型助成"],
  },
  {
    id: "nedo-tcp",
    name: "NEDO TCP（Technology Commercialization Program）",
    nameEn: "NEDO TCP",
    operator: "新エネルギー・産業技術総合開発機構（NEDO）",
    region: "全国",
    assetTypes: ["talent-program", "mentoring", "community"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年プログラム・イベント形式で実施",
    },
    value: "技術シーズの事業化教育・メンタリング・発表機会",
    eligibility: "技術を基に起業・事業拡大を目指す研究者・起業家予備群",
    summary:
      "技術シーズを持つ研究者や起業家予備群に、事業化知識の教育、ビジネスプラン作成支援、大企業・VC等への発表やマッチング機会を提供するNEDOの入口プログラム。",
    url: "https://www.nedo.go.jp/activities/ZZJP2_100103.html",
    tags: ["ディープテック", "事業化", "起業家教育"],
  },
  {
    id: "tokyo-sogyo-grant",
    name: "東京都 創業助成事業",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "upcoming",
      opensAt: "2026-09-29",
      deadline: "2026-10-08",
      window: "毎年 4月・10月頃の年2回",
      note: "第2回（令和8年度）の申請受付。第1回は4/16で終了",
    },
    value: "上限400万円・助成率2/3（年度により変動）",
    eligibility: "都内で創業予定/創業初期かつ一定要件を満たす者",
    summary:
      "都内の創業初期に必要な経費（人件費・賃借料・広告費等）の一部を助成。TOKYO創業ステーション等の支援を受けていることが要件になる場合がある。",
    url: "https://startup-station.jp/m/sogyojosei/",
    tags: ["東京都", "助成金"],
  },
  {
    id: "smrj-fastar",
    name: "中小機構 FASTAR",
    nameEn: "FASTAR",
    operator: "中小企業基盤整備機構（中小機構）",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "grant-subsidy"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（ギア期ごと）",
    },
    value: "公的アクセラによる非エクイティの集中伴走",
    eligibility: "成長を目指すスタートアップ・中小企業",
    summary:
      "中小機構が運営する非エクイティのアクセラレーション。専属サポーターによる事業計画づくりや資金調達準備の集中伴走を無償で提供する。",
    url: "https://fastar.smrj.go.jp/",
    tags: ["公的支援", "非エクイティ"],
  },
  {
    id: "sbir",
    name: "SBIR制度（中小企業技術革新制度）",
    nameEn: "SBIR",
    operator: "内閣府 / 各省庁",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "各省庁の指定補助金として年次公募",
    },
    value: "研究開発補助＋随意契約等の出口支援",
    eligibility: "研究開発に取り組むスタートアップ・中小企業",
    summary:
      "国の研究開発予算をスタートアップ等に重点配分する制度。各省庁の指定補助金を通じた研究開発フェーズ別の支援と、公共調達への接続を図る。",
    url: "https://www8.cao.go.jp/cstp/sbir/index.html",
    tags: ["研究開発", "公共調達"],
  },
  {
    id: "go-tech",
    name: "成長型中小企業等研究開発支援事業（Go-Tech）",
    nameEn: "Go-Tech",
    operator: "中小企業庁 / 経済産業局",
    region: "全国",
    assetTypes: ["grant-subsidy", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年度ごとに公募",
      note: "令和8年度公募情報は各経済産業局・中小企業庁サイトで確認",
    },
    value: "大学・公設試等と連携する研究開発を最大3年間支援",
    eligibility: "中小企業・スタートアップ等を中心とする共同体（研究機関連携）",
    summary:
      "中小企業等が大学・公設試等と連携して行う、事業化につながる研究開発・試作品開発・販路開拓を支援する制度。ものづくり・サービス系の技術開発スタートアップに有用。",
    url: "https://www.chusho.meti.go.jp/sapoin/index.php/about/",
    tags: ["研究開発", "補助金", "大学連携"],
  },
  {
    id: "jfc-startup-loan",
    name: "日本公庫 スタートアップ支援資金 / 新規開業資金",
    operator: "日本政策金融公庫",
    region: "全国",
    assetTypes: ["funding"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申込）" },
    value: "創業・成長期向けの融資（条件により無担保・無保証）",
    eligibility: "創業予定者・スタートアップ",
    summary:
      "政府系金融機関による創業・スタートアップ向け融資制度。新規開業資金など、創業期でも利用しやすい条件のメニューが用意されている。",
    url: "https://www.jfc.go.jp/n/finance/search/startup.html",
    tags: ["融資", "公的金融"],
  },
  {
    id: "monozukuri-hojokin",
    name: "ものづくり・商業・サービス生産性向上促進補助金",
    operator: "中小企業庁 / 全国中央会",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "公募回ごと（年数回）",
      note: "2026年度以降は新事業進出補助金との統合・再編が予定",
    },
    value: "設備投資・試作開発費の補助（枠により数百万〜数千万円）",
    eligibility: "中小企業・小規模事業者（要件あり）",
    summary:
      "革新的な製品・サービス開発や生産プロセス改善のための設備投資等を補助する代表的な補助金。グローバル枠など複数の申請枠がある。",
    url: "https://portal.monodukuri-hojo.jp/",
    tags: ["補助金", "設備投資"],
  },
  {
    id: "shinjigyou-shinshutsu",
    name: "中小企業新事業進出補助金",
    operator: "中小企業基盤整備機構 / 中小企業庁",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "公募回ごと（2026年は複数回実施）",
      note: "第4回公募の申請受付は2026/6/19で終了。次回は公式サイトで確認",
    },
    value: "新製品・新市場進出等に最大9,000万円規模の補助",
    eligibility: "既存事業と異なる新市場・新製品等へ挑戦する中小企業等",
    summary:
      "既存事業の枠を超えた新製品開発・新市場進出・新規事業への大胆な挑戦を支援する補助金。建物費、機械装置、システム構築費など幅広い投資を対象にする。",
    url: "https://shinjigyou-shinshutsu.smrj.go.jp/",
    tags: ["補助金", "新規事業", "設備投資"],
  },
  {
    id: "it-donyu-hojokin",
    name: "IT導入補助金",
    operator: "中小企業庁 / 中小機構",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年 複数の締切回で公募",
    },
    value: "ITツール・ソフトウェア導入費の補助",
    eligibility: "中小企業・小規模事業者",
    summary:
      "業務効率化やDXに資するITツール（会計・受発注・決済・ECなど）の導入費用を補助する制度。登録されたITツール・ベンダーを通じて申請する。",
    url: "https://it-shien.smrj.go.jp/",
    tags: ["補助金", "DX"],
  },
  {
    id: "shoryokuka-hojokin",
    name: "中小企業省力化投資補助金（一般型）",
    operator: "中小企業庁 / 中小機構",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "upcoming",
      opensAt: "2026-07-01",
      window: "公募回ごと（2026年7月上旬〜下旬に第7回申請受付予定）",
    },
    value: "人手不足対応・自動化/省力化投資の補助",
    eligibility: "人手不足解消に資する設備・システム投資を行う中小企業等",
    summary:
      "IoT、ロボット、設備、システムなどによる省力化投資を支援する補助金。オペレーション改善や労働集約的業務の自動化に取り組むスタートアップにも検討余地がある。",
    url: "https://www.chusho.meti.go.jp/koukai/hojyokin/index.html",
    tags: ["補助金", "省力化", "自動化"],
  },
  {
    id: "jizokuka-sogyo",
    name: "小規模事業者持続化補助金（創業型）",
    operator: "中小企業庁 / 商工会・商工会議所",
    region: "全国",
    assetTypes: ["grant-subsidy", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "upcoming",
      opensAt: "2026-11-05",
      deadline: "2026-12-15",
      window: "公募回ごと",
      note: "第4回創業型の申請受付期間",
    },
    value: "販路開拓・業務効率化等の小規模補助",
    eligibility: "創業後間もない小規模事業者（創業支援等事業の修了要件あり）",
    summary:
      "創業直後の小規模事業者による販路開拓、広報、EC、店舗改装、業務効率化などを支援する補助金。スタートアップというよりスモールビジネス寄りだが、創業初期の資金繰りに有用。",
    url: "https://www.chusho.meti.go.jp/koukai/hojyokin/index.html",
    tags: ["補助金", "創業型", "販路開拓"],
  },
  {
    id: "chusho-toshi-ikusei",
    name: "中小企業投資育成",
    operator: "中小企業投資育成株式会社（東京/名古屋/大阪）",
    region: "全国",
    assetTypes: ["equity-investment", "funding"],
    stages: ["early", "growth"],
    equity: "optional",
    application: { status: "rolling", note: "通年（随時相談・審査）" },
    value: "安定株主としての長期・中立な出資",
    eligibility: "成長を目指す中小企業・スタートアップ",
    summary:
      "国の政策に基づき設立された公的色の強い投資会社。経営の自主性を尊重しつつ、長期保有を前提とした安定株主として出資し、増資や事業承継の局面を支える。",
    url: "https://www.sbic.co.jp/",
    tags: ["出資あり", "公的金融"],
  },

  // ===================================================================
  // 女性起業家・地方エコシステム
  // ===================================================================
  {
    id: "giraffes-japan",
    name: "GIRAFFES JAPAN（女性アントレプレナー地域密着型支援）",
    nameEn: "GIRAFFES JAPAN",
    operator: "経済産業省",
    region: "全国（8地域）",
    assetTypes: ["talent-program", "mentoring", "community"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "全国8地域で年度ごとにプログラム・イベントを実施",
    },
    value: "女性起業家と支援者の地域密着型プログラム",
    eligibility: "女性起業家・起業を目指す女性・地域支援者",
    summary:
      "経産省の女性起業家支援事業。北海道、東北、関東、中部、近畿、中国、四国、九州の8地域で、女性起業家と支援者がともに学び成長する支援プロセスを展開する。",
    url: "https://www.meti.go.jp/policy/economy/jinzai/joseikigyouka/index.html",
    tags: ["女性起業家", "地域支援", "経産省"],
  },
  {
    id: "apt-women",
    name: "APT Women",
    operator: "東京都",
    region: "東京",
    assetTypes: ["accelerator", "mentoring", "overseas", "community"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（3ヶ月程度の成長支援プログラム）",
    },
    value: "女性ベンチャー向け講義・メンタリング・海外展開支援",
    eligibility: "事業成長・スケールアップを目指す女性起業家",
    summary:
      "東京都による女性ベンチャー成長促進事業。講義、メンタリング、受講生コミュニティ、海外展開を見据えた経営力強化を通じて、女性起業家のスケールアップを支援する。",
    url: "https://apt-women.metro.tokyo.lg.jp/",
    tags: ["女性起業家", "東京都", "海外展開"],
  },
  {
    id: "led-kansai",
    name: "LED関西 女性起業家応援プロジェクト",
    nameEn: "LED関西",
    operator: "近畿経済産業局 ほか",
    region: "関西",
    assetTypes: ["community", "mentoring", "talent-program"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年キックオフ〜ビジネスプラン発表会を実施",
    },
    value: "女性起業家の発表機会・継続コミュニティ・支援者接続",
    eligibility: "関西圏の女性起業家・起業を目指す女性",
    summary:
      "関西の女性起業家を対象にした応援プロジェクト。ビジネスプラン発表会を中心に、100名超の過去ファイナリストや多数のサポーター企業・支援団体との継続的なネットワークを提供する。",
    url: "https://ledkansai.jp/",
    tags: ["女性起業家", "関西", "コミュニティ"],
  },
  {
    id: "shibuya-herrise",
    name: "渋谷区女性起業家育成プログラム HerRise",
    nameEn: "HerRise",
    operator: "渋谷区",
    region: "東京（渋谷）",
    assetTypes: ["talent-program", "mentoring", "community"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "令和8年度は全6回開催、女性起業家向けイベントも予定",
    },
    value: "女性起業家向け連続ワークショップ・相談・交流",
    eligibility: "スタートアップとして起業中、または起業を目指す女性",
    summary:
      "渋谷区が実施する、世界を目指す女性起業家・スタートアップ経営者向けの実践型プログラム。連続ワークショップ、セミナー、支援拠点開放、相談・交流の場を提供する。",
    url: "https://www.city.shibuya.tokyo.jp/jigyosha/shoko-rodo-sodan/startup/entrepreneurship_program.html",
    tags: ["女性起業家", "渋谷", "起業家教育"],
  },
  {
    id: "startup-hokkaido",
    name: "STARTUP HOKKAIDO",
    operator: "STARTUP HOKKAIDO実行委員会（札幌市・北海道・北海道経済産業局）",
    region: "北海道（札幌）",
    assetTypes: ["community", "mentoring", "accelerator"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "相談・イベント・プログラムを随時実施" },
    value: "北海道のスタートアップ相談・イベント・一次産業/食領域支援",
    eligibility: "北海道で創業・成長を目指す起業家・スタートアップ",
    summary:
      "札幌市、北海道、北海道経済産業局が一体で進める地域エコシステム。スタートアップ相談、イベント、一次産業・食領域のアクセラ連携などを通じて、北海道発スタートアップを支援する。",
    url: "https://startuphokkaido.com/",
    tags: ["北海道", "地方拠点", "一次産業"],
  },
  {
    id: "sendai-startup-studio",
    name: "仙台スタートアップスタジオ",
    operator: "仙台市 ほか",
    region: "東北（仙台）",
    assetTypes: ["accelerator", "mentoring", "community", "overseas"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "プログラム・イベントを随時実施" },
    value: "東北発スタートアップの伴走・経営者メンタリング・発信機会",
    eligibility: "仙台・東北で創業・成長を目指すスタートアップ",
    summary:
      "仙台・東北発スタートアップを支援する地域拠点。地元経営者によるアドバイス、プログラム、ピッチ/イベント、国内外への発信機会を通じて成長を後押しする。",
    url: "https://sendaistartupstudio.com/",
    tags: ["仙台", "東北", "地方拠点"],
  },
  {
    id: "hyogo-kobe-startup-fund",
    name: "ひょうご神戸スタートアップファンド",
    operator: "兵庫県 / 神戸市 / 民間ファンド運営者",
    region: "兵庫（神戸）",
    assetTypes: ["equity-investment", "funding", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "required",
    application: { status: "rolling", note: "投資検討は随時。詳細は運営者・自治体情報を確認" },
    value: "兵庫・神戸発スタートアップへの地域ファンド投資",
    eligibility: "兵庫・神戸から成長を目指す、または地域連携を行うスタートアップ",
    summary:
      "兵庫県・神戸市が民間企業等と連携して設立した地域スタートアップファンド。地域経済活性化と県内産業の競争力向上を目的に、飛躍的成長が見込まれるスタートアップへ投資する。",
    url: "https://web.pref.hyogo.lg.jp/sr10/hksf.html",
    tags: ["神戸", "地方ファンド", "出資あり"],
  },
  {
    id: "life-tech-kobe",
    name: "Life-Tech KOBE",
    operator: "神戸市",
    region: "兵庫（神戸）",
    assetTypes: ["grant-subsidy", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年度ごとに補助・実証・支援メニューを実施",
    },
    value: "ライフテック領域の補助・実証・事業所開設支援",
    eligibility: "高度なテクノロジーを活用するライフテック系スタートアップ",
    summary:
      "神戸市のライフテック系スタートアップ支援。事業所開設補助、実証・連携、ひょうご神戸スタートアップファンド等への導線を通じて、医療・健康・生活領域の事業成長を支援する。",
    url: "https://life-techkobe.smartkobe-portal.com/services/",
    tags: ["神戸", "ライフテック", "実証"],
  },

  // ===================================================================
  // 大学発・アカデミア出資
  // ===================================================================
  {
    id: "kyoto-icap",
    name: "京都大学イノベーションキャピタル（Kyoto-iCAP）",
    nameEn: "Kyoto-iCAP",
    operator: "京都大学イノベーションキャピタル株式会社",
    region: "関西（京都）",
    assetTypes: ["equity-investment", "grant-subsidy", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "GAPファンド等は公募、出資は随時検討",
    },
    value: "京大関連の研究シーズへの出資＋GAPファンド",
    eligibility: "京都大学の研究成果を活用するスタートアップ・研究者",
    summary:
      "京都大学公認のベンチャーキャピタル。大学の研究成果の事業化を、ギャップファンドによる初期支援やシード/アーリーの出資、ハンズオン支援で後押しする。",
    url: "https://www.kyoto-unicap.co.jp/",
    tags: ["大学発", "ディープテック"],
  },
  {
    id: "keio-innovation",
    name: "慶應イノベーション・イニシアティブ（KII）",
    nameEn: "KII",
    operator: "株式会社慶應イノベーション・イニシアティブ",
    region: "全国",
    assetTypes: ["equity-investment", "mentoring"],
    stages: ["seed", "early"],
    equity: "required",
    application: { status: "rolling", note: "随時、投資を検討" },
    value: "慶應関連の研究シーズ・スタートアップへの出資",
    eligibility: "慶應義塾の研究成果を基盤とするスタートアップ",
    summary:
      "慶應義塾大学発のスタートアップを主な投資対象とするベンチャーキャピタル。大学の研究シーズの事業化に向けて出資とハンズオン支援を行う。",
    url: "https://www.keio-innovation.co.jp/",
    tags: ["大学発", "出資あり"],
  },
  {
    id: "tongali",
    name: "Tongali（東海地区大学アントレ）",
    nameEn: "Tongali",
    operator: "名古屋大学 ほか東海地区大学連携",
    region: "東海（名古屋）",
    assetTypes: ["talent-program", "community", "grant-subsidy", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年プログラム・ビジネスプランコンテストを開催",
    },
    value: "アントレ教育・ギャップファンド・伴走支援",
    eligibility: "東海地区の大学に関係する学生・研究者",
    summary:
      "名古屋大学を中心とした東海地区の大学連携アントレプレナーシップ事業。起業家教育プログラム、ビジネスプランコンテスト、事業化に向けたギャップファンドを提供する。",
    url: "https://tongali.net/",
    tags: ["大学発", "アントレ教育"],
  },

  // ===================================================================
  // 横断データベース・情報ハブ
  // ===================================================================
  {
    id: "meti-startup-list",
    name: "経済産業省 スタートアップ支援策一覧",
    operator: "経済産業省",
    region: "全国",
    assetTypes: ["grant-subsidy", "community"],
    stages: ["any"],
    equity: "none",
    application: {
      status: "rolling",
      note: "情報資料（随時更新・カオスマップ）",
    },
    value: "補助金・融資・税制など官系施策を一覧化",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "補助金・融資・税制など官系の支援策を網羅的にまとめた公式資料。フェーズ別に使える制度を俯瞰できる。本サイトの官系情報の一次ソース。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["公式", "一次ソース"],
  },
  {
    id: "startup-portal-cas",
    name: "スタートアップ育成ポータルサイト",
    operator: "内閣官房 / 内閣府",
    region: "全国",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "情報ポータル（通年）" },
    value: "5か年計画ベースの政府支援への入口",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "スタートアップ育成5か年計画に基づく政府の各種取組をまとめた公式ポータル。各省庁の施策や拠点構想への導線を提供する。",
    url: "https://www.cas.go.jp/jp/seisaku/su-portal/index.html",
    tags: ["政府", "ポータル"],
  },
  {
    id: "foundx-resources",
    name: "FoundX Startup Resources",
    operator: "東京大学 FoundX",
    region: "全国",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "ナレッジDB（通年・無償）" },
    value: "300本以上の起業ノウハウ・翻訳カリキュラム",
    eligibility: "すべての起業家",
    summary:
      "起業家のためのナレッジまとめサイト。Startup School等の翻訳教材や、資金調達・採用などのノウハウ記事が体系的に整理されている。",
    url: "https://resource.foundx.jp/",
    tags: ["ナレッジ", "学習"],
  },
  {
    id: "mirasapo-plus",
    name: "ミラサポplus",
    operator: "中小企業庁",
    region: "全国",
    assetTypes: ["grant-subsidy", "community"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "情報ポータル（通年・無償）" },
    value: "補助金・支援制度の検索と申請情報",
    eligibility: "すべての中小企業・起業家",
    summary:
      "中小企業庁が運営する中小企業向け支援情報の総合サイト。補助金・給付金の検索、申請手続き、支援機関情報などを一元的に提供し、自社に合う制度を探せる。",
    url: "https://mirasapo-plus.go.jp/",
    tags: ["公式", "補助金検索"],
  },
  {
    id: "j-net21",
    name: "J-Net21",
    operator: "中小企業基盤整備機構（中小機構）",
    region: "全国",
    assetTypes: ["community", "grant-subsidy"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "情報ポータル（通年・無償）" },
    value: "創業・経営ノウハウと支援制度・補助金情報",
    eligibility: "すべての起業家・中小企業",
    summary:
      "中小機構が運営する中小企業・起業家向けの総合情報サイト。創業の手引き、経営ノウハウ、全国の補助金・支援施策の検索など、実務に直結する情報を網羅する。",
    url: "https://j-net21.smrj.go.jp/",
    tags: ["公的支援", "ナレッジ"],
  },

  // ===================================================================
  // 海外アクセラレーター・ファンド（日本から応募可能）
  // ===================================================================
  {
    id: "y-combinator",
    name: "Y Combinator",
    nameEn: "Y Combinator",
    operator: "Y Combinator",
    region: "米国（シリコンバレー）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["idea", "seed", "early"],
    equity: "required",
    application: {
      status: "recurring",
      window: "年2回前後のバッチ。締切前のローリング選考",
    },
    value: "標準条件で約50万ドルの出資＋3ヶ月プログラム",
    eligibility: "世界中の創業者（国籍・拠点不問）。英語での選考",
    summary:
      "世界で最も著名なスタートアップアクセラレーター。標準ディールでの出資、3ヶ月の集中プログラム、Demo Day、強力な卒業生ネットワークを提供する。日本を含め世界中から応募できる。",
    url: "https://www.ycombinator.com/",
    tags: ["グローバル", "シリコンバレー", "トップティア"],
  },
  {
    id: "techstars",
    name: "Techstars",
    nameEn: "Techstars",
    operator: "Techstars",
    region: "グローバル（各都市プログラム）",
    assetTypes: ["accelerator", "equity-investment", "mentoring", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "recurring",
      window: "都市・テーマ別プログラムごとに通年でコホート募集",
    },
    value: "出資＋13週間のメンタードリブン・プログラム",
    eligibility: "アーリー期スタートアップ（世界各地のプログラムに応募）",
    summary:
      "世界各都市・各テーマで展開するメンター主導型アクセラレーター。出資、13週間の集中支援、世界規模のメンター/投資家ネットワークへのアクセスを提供する。",
    url: "https://www.techstars.com/",
    tags: ["グローバル", "メンタリング"],
  },
  {
    id: "entrepreneur-first",
    name: "Entrepreneur First (EF)",
    nameEn: "Entrepreneur First",
    operator: "Entrepreneur First",
    region: "グローバル（ロンドン/シンガポール等）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "各拠点でコホート制。共同創業者探しから開始",
    },
    value: "創業前の個人への支援＋出資",
    eligibility: "起業を志す個人（チーム未結成でも可）",
    summary:
      "「タレント・インベスター」を掲げ、まだチームもアイデアも無い優秀な個人を集めて、共同創業者の組成から会社設立・出資までを支援するグローバルプログラム。",
    url: "https://www.joinef.com/",
    tags: ["グローバル", "共同創業", "タレント"],
  },
  {
    id: "berkeley-skydeck",
    name: "Berkeley SkyDeck",
    nameEn: "Berkeley SkyDeck",
    operator: "UC Berkeley",
    region: "米国（バークレー）",
    assetTypes: ["accelerator", "equity-investment", "mentoring", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "recurring",
      window: "Batch/Pad-13 等を定期募集（海外スタートアップの採択実績多数）",
    },
    value: "大規模コホートでの出資＋6ヶ月の支援",
    eligibility: "世界中のスタートアップ（大学関係者でなくても応募可）",
    summary:
      "UCバークレー公式のアクセラレーター。出資、アドバイザー・ネットワーク、Demo Dayを提供する。海外スタートアップの受け入れにも積極的で、日本からの採択実績もある。",
    url: "https://skydeck.berkeley.edu/",
    tags: ["グローバル", "大学発", "バークレー"],
  },
  {
    id: "alchemist-accelerator",
    name: "Alchemist Accelerator",
    nameEn: "Alchemist Accelerator",
    operator: "Alchemist Accelerator",
    region: "米国（シリコンバレー）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "recurring",
      window: "通年でクラスを募集（B2B/エンタープライズ特化）",
    },
    value: "出資＋6ヶ月のB2B特化プログラム",
    eligibility: "売上が企業から発生するB2B/エンタープライズ系スタートアップ",
    summary:
      "エンタープライズ・B2Bに特化したシリコンバレーのアクセラレーター。出資、顧客・投資家への接続、Demo Dayを提供する。",
    url: "https://www.alchemistaccelerator.com/",
    tags: ["グローバル", "B2B", "エンタープライズ"],
  },
  {
    id: "sosv-hax",
    name: "HAX (SOSV)",
    nameEn: "HAX",
    operator: "SOSV",
    region: "米国（ニューアーク）/ グローバル",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "rolling",
      note: "ハードテック特化。通年で応募を受付",
    },
    value: "出資＋ハードウェア量産化の伴走支援",
    eligibility: "ハードテック・ディープテック系スタートアップ",
    summary:
      "ベンチャーファンドSOSVが運営するハードテック特化プログラム。試作から量産化までのエンジニアリング支援と出資を提供する。",
    url: "https://hax.co/",
    tags: ["グローバル", "ハードウェア", "ディープテック"],
  },
  {
    id: "sosv-indiebio",
    name: "IndieBio (SOSV)",
    nameEn: "IndieBio",
    operator: "SOSV",
    region: "米国（サンフランシスコ/ニューヨーク）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "バイオ/ライフサイエンス特化でコホート募集",
    },
    value: "出資＋ウェットラボを備えた4〜6ヶ月プログラム",
    eligibility: "バイオ・ライフサイエンス・食料/気候テック系",
    summary:
      "SOSVが運営する世界有数のバイオテック・アクセラレーター。出資に加えウェットラボや専門メンターを提供し、サイエンス系の創業を支援する。",
    url: "https://indiebio.co/",
    tags: ["グローバル", "バイオ", "ディープテック"],
  },
  {
    id: "orbit-startups",
    name: "Orbit Startups",
    nameEn: "Orbit Startups",
    operator: "SOSV",
    region: "アジア太平洋・新興国市場",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "rolling",
      note: "旧 MOX。アジア新興国展開を志向するチームを通年で受付",
    },
    value: "出資＋アジア新興国へのグロース支援",
    eligibility: "アジア太平洋・新興国市場への展開を狙うスタートアップ",
    summary:
      "SOSV傘下のグロース特化プログラム（旧MOX）。アジア太平洋・新興国市場でのユーザー獲得や事業拡大を、出資とパートナー網で支援する。",
    url: "https://orbitstartups.com/",
    tags: ["グローバル", "アジア", "市場展開"],
  },
  {
    id: "masschallenge",
    name: "MassChallenge",
    nameEn: "MassChallenge",
    operator: "MassChallenge",
    region: "米国/グローバル",
    assetTypes: ["accelerator", "mentoring", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "各拠点で年次プログラムを公募",
    },
    value: "非エクイティの伴走支援＋賞金機会",
    eligibility: "幅広い業種のアーリー期スタートアップ",
    summary:
      "株式を取得しない（エクイティ・フリー）ことで知られるグローバル・アクセラレーター。メンタリング、ネットワーク、表彰・賞金を提供する。",
    url: "https://masschallenge.org/",
    tags: ["グローバル", "非エクイティ", "メンタリング"],
  },
  {
    id: "founder-institute",
    name: "Founder Institute",
    nameEn: "Founder Institute",
    operator: "Founder Institute",
    region: "グローバル（東京チャプター含む）",
    assetTypes: ["accelerator", "mentoring", "community", "overseas"],
    stages: ["idea", "seed"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "各都市（東京含む）で定期コホートを募集",
    },
    value: "創業前向けの構造化されたプレシード・プログラム",
    eligibility: "アイデア〜創業初期の起業家（在職中でも参加可）",
    summary:
      "世界各都市で展開する創業前特化のプレシード・プログラム。週次の課題とメンタリングで会社設立・立ち上げを伴走する。東京チャプターもある。",
    url: "https://fi.co/",
    tags: ["グローバル", "プレシード", "メンタリング"],
  },
  {
    id: "draper-university",
    name: "Draper University",
    nameEn: "Draper University",
    operator: "Draper University",
    region: "米国（サンマテオ）",
    assetTypes: ["accelerator", "community", "talent-program", "overseas"],
    stages: ["idea", "seed"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "起業家養成プログラムを定期開催（海外参加者多数）",
    },
    value: "起業家マインドセットの集中プログラム＋投資機会",
    eligibility: "世界中の起業志望者・アーリー創業者",
    summary:
      "著名投資家ティム・ドレイパーが設立した起業家養成校。集中合宿型のプログラムでマインドセットやネットワークを養い、投資機会にもつなげる。海外からの参加者が多い。",
    url: "https://www.draperuniversity.com/",
    tags: ["グローバル", "起業家教育", "シリコンバレー"],
  },
  {
    id: "a16z-speedrun",
    name: "a16z Speedrun",
    nameEn: "a16z Speedrun",
    operator: "Andreessen Horowitz (a16z)",
    region: "米国（サンフランシスコ）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "テック/ゲーム/AI系のコホートを定期募集",
    },
    value: "最大約100万ドルの出資＋12週間プログラム",
    eligibility: "テック系（特にAI・ゲーム・消費者向け）の創業者",
    summary:
      "トップVCのa16zが運営するアクセラレーター。出資、a16zパートナー・ネットワークへのアクセス、12週間の集中プログラムを提供する。",
    url: "https://a16z.com/speedrun/",
    tags: ["グローバル", "AI", "トップティア"],
  },
  {
    id: "south-park-commons",
    name: "South Park Commons",
    nameEn: "South Park Commons",
    operator: "South Park Commons",
    region: "米国（サンフランシスコ/ニューヨーク）",
    assetTypes: ["community", "equity-investment", "overseas"],
    stages: ["idea", "seed"],
    equity: "optional",
    application: {
      status: "rolling",
      note: "Founder Fellowship 等を通年で受付",
    },
    value: "創業前の「ゼロから1」期を支える出資＋コミュニティ",
    eligibility: "次の事業を模索する技術者・起業家",
    summary:
      "アイデア前夜の「ゼロから1」期に特化したコミュニティ兼ファンド。Founder Fellowshipでの出資と、強力な技術者・起業家コミュニティを提供する。",
    url: "https://www.southparkcommons.com/",
    tags: ["グローバル", "プレアイデア", "コミュニティ"],
  },
  {
    id: "sequoia-arc",
    name: "Sequoia Arc",
    nameEn: "Arc",
    operator: "Sequoia Capital",
    region: "米国/欧州",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "シード特化のコホートを定期募集",
    },
    value: "シード出資＋セコイアの集中支援プログラム",
    eligibility: "アウトライアーを志すシード期の創業者",
    summary:
      "トップVCセコイアによるシード期スタートアップ向けプログラム。出資に加え、プロダクト・採用・GTMなどの集中カリキュラムとネットワークを提供する。",
    url: "https://www.sequoiacap.com/arc/",
    tags: ["グローバル", "シード", "トップティア"],
  },
  {
    id: "station-f",
    name: "STATION F Founders Program",
    nameEn: "STATION F",
    operator: "STATION F",
    region: "フランス（パリ）",
    assetTypes: ["free-office", "accelerator", "community", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "世界最大級のスタートアップキャンパス。プログラムを定期募集",
    },
    value: "パリの巨大キャンパスのデスク＋プログラム",
    eligibility: "欧州展開を志す世界中のスタートアップ",
    summary:
      "世界最大級のスタートアップ・キャンパス。Founders Programではデスク、メンタリング、投資家・大企業ネットワークを提供し、欧州進出の足がかりになる。",
    url: "https://stationf.co/",
    tags: ["グローバル", "欧州展開", "キャンパス"],
  },
  {
    id: "outlier-ventures",
    name: "Outlier Ventures Base Camp",
    nameEn: "Outlier Ventures",
    operator: "Outlier Ventures",
    region: "グローバル（リモート）",
    assetTypes: ["accelerator", "equity-investment", "overseas"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "rolling",
      note: "Web3/分散型・AI系のコホートを通年で受付",
    },
    value: "出資＋トークンエコノミー設計などの伴走支援",
    eligibility: "Web3・分散型・AI領域のスタートアップ",
    summary:
      "Web3・分散型テック特化の世界的アクセラレーター。トークン設計、GTM、投資家接続を含む集中プログラムと出資を提供する。",
    url: "https://outlierventures.io/",
    tags: ["グローバル", "Web3", "リモート"],
  },
  {
    id: "alliance-dao",
    name: "Alliance DAO",
    nameEn: "Alliance DAO",
    operator: "Alliance",
    region: "グローバル（リモート）",
    assetTypes: ["accelerator", "equity-investment", "community", "overseas"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "クリプト/Web3特化でコホートを定期募集",
    },
    value: "出資＋クリプト創業者コミュニティ",
    eligibility: "クリプト・Web3領域の創業者",
    summary:
      "クリプト/Web3に特化した世界有数のアクセラレーター兼創業者コミュニティ。出資、メンタリング、エコシステム内ネットワークを提供する。",
    url: "https://alliance.xyz/",
    tags: ["グローバル", "Web3", "クリプト"],
  },

  // ===================================================================
  // 海外SaaS・クラウドのスタートアップ向けクレジット/特典
  // ===================================================================
  {
    id: "stripe-atlas",
    name: "Stripe Atlas",
    nameEn: "Stripe Atlas",
    operator: "Stripe",
    region: "グローバル（米デラウェア法人設立）",
    assetTypes: ["overseas", "community"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "rolling",
      note: "随時申込可（実費あり）。日本からの米国法人設立に利用される",
    },
    value: "米国法人の設立・銀行口座・各種SaaS特典をまとめて",
    eligibility: "米国法人を設立したい世界中の創業者",
    summary:
      "米デラウェア法人の設立、EIN取得、銀行口座開設、株式発行までをオンラインで完結できるサービス。提携SaaSのクレジット特典も付属し、海外展開の起点になる。",
    url: "https://stripe.com/atlas",
    tags: ["グローバル", "法人設立", "米国進出"],
  },
  {
    id: "digitalocean-hatch",
    name: "DigitalOcean Hatch",
    nameEn: "DigitalOcean Hatch",
    operator: "DigitalOcean",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "随時申請可。条件によりクレジット額が変動",
    },
    value: "最大数千ドル規模のクラウドクレジット＋特典",
    eligibility: "創業初期のスタートアップ",
    summary:
      "DigitalOceanのスタートアップ支援プログラム。クラウドクレジット、技術サポート、コミュニティやメンタリングへのアクセスを提供する。",
    url: "https://www.digitalocean.com/hatch",
    tags: ["クラウド", "クレジット"],
  },
  {
    id: "twilio-startups",
    name: "Twilio Startups",
    nameEn: "Twilio for Startups",
    operator: "Twilio",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "提携VC/アクセラレーター経由などで申請",
    },
    value: "Twilio/SendGrid/Segment のクレジット＋サポート",
    eligibility: "一定条件を満たすアーリー期スタートアップ",
    summary:
      "通信API大手Twilioのスタートアップ支援。Twilio・SendGrid・Segmentのクレジット、技術サポート、教育リソースを提供する。",
    url: "https://www.twilio.com/en-us/startups",
    tags: ["クラウド", "通信API", "クレジット"],
  },
  {
    id: "atlassian-startups",
    name: "Atlassian for Startups",
    nameEn: "Atlassian for Startups",
    operator: "Atlassian",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "対象VC/アクセラレーターのポートフォリオ等が対象",
    },
    value: "Jira/Confluence等を一定人数まで無料",
    eligibility: "条件を満たすアーリー期スタートアップ",
    summary:
      "AtlassianのスタートアッププログラムでJira・Confluence・各種ツールを一定規模まで無償提供。チームの開発・ドキュメント基盤を低コストで整えられる。",
    url: "https://www.atlassian.com/software/startups",
    tags: ["SaaS", "開発ツール", "クレジット"],
  },
  {
    id: "intercom-early-stage",
    name: "Intercom Early Stage",
    nameEn: "Intercom Early Stage",
    operator: "Intercom",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "創業年数・資金調達額などの条件あり",
    },
    value: "初年度に大幅割引でIntercomを利用",
    eligibility: "創業初期（資金調達・人数等の条件あり）のスタートアップ",
    summary:
      "顧客コミュニケーション基盤Intercomの初期スタートアップ向け割引プログラム。初年度を大幅ディスカウントで導入できる。",
    url: "https://www.intercom.com/early-stage",
    tags: ["SaaS", "カスタマーサポート", "割引"],
  },
  {
    id: "algolia-startup",
    name: "Algolia Startup Program",
    nameEn: "Algolia for Startups",
    operator: "Algolia",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "創業初期・小規模を対象に申請受付",
    },
    value: "検索API Algoliaのクレジット/無償枠",
    eligibility: "条件を満たすアーリー期スタートアップ",
    summary:
      "検索・レコメンドAPI大手Algoliaのスタートアップ支援。一定期間のクレジットやサポートを提供し、プロダクトの検索体験を素早く構築できる。",
    url: "https://www.algolia.com/",
    tags: ["SaaS", "検索API", "クレジット"],
  },
  {
    id: "snowflake-startups",
    name: "Snowflake Startup Program",
    nameEn: "Snowflake for Startups",
    operator: "Snowflake",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "データ基盤を構築するアーリー期を対象に申請受付",
    },
    value: "Snowflakeのクレジット＋技術支援",
    eligibility: "条件を満たすアーリー期スタートアップ",
    summary:
      "データクラウドSnowflakeのスタートアップ支援。クレジット、技術サポート、共同マーケティングの機会を提供する。",
    url: "https://www.snowflake.com/startups/",
    tags: ["クラウド", "データ基盤", "クレジット"],
  },
  {
    id: "posthog-startups",
    name: "PostHog for Startups",
    nameEn: "PostHog for Startups",
    operator: "PostHog",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "rolling",
      note: "創業年数・資金調達額などの条件あり",
    },
    value: "プロダクト分析の大型無償クレジット＋特典",
    eligibility: "創業初期（資金調達・年数の条件あり）のスタートアップ",
    summary:
      "プロダクト分析・実験基盤PostHogのスタートアップ支援。大型の無償クレジットや限定特典を提供し、初期のデータ計測を低コストで始められる。",
    url: "https://posthog.com/startups",
    tags: ["SaaS", "プロダクト分析", "クレジット"],
  },
  {
    id: "oracle-startups",
    name: "Oracle for Startups",
    nameEn: "Oracle for Startups",
    operator: "Oracle",
    region: "グローバル",
    assetTypes: ["cloud-credit", "overseas"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "随時申請可。クラウドクレジットと支援を提供",
    },
    value: "OCIクラウドクレジット＋技術/GTM支援",
    eligibility: "アーリー〜グロース期のスタートアップ",
    summary:
      "Oracle Cloud Infrastructure(OCI)のクレジット、技術サポート、共同マーケティング機会を提供するスタートアップ支援プログラム。",
    url: "https://www.oracle.com/startup/",
    tags: ["クラウド", "クレジット"],
  },
];
