import type { Asset } from "./types";

// 日本の起業家・スタートアップが使える支援アセットのキュレーション済みデータ。
// 内容は変動するため、申込条件・金額・募集時期などの最新情報は必ず各公式サイトを確認してください。
// データの追加・修正は GitHub への Pull Request を歓迎します。
// 最終確認: 2026-06

export const assets: Asset[] = [
  // ===== 無料オフィス・インキュベーション =====
  {
    id: "flap",
    name: "FLAP",
    operator: "mint（旧 Apricot Ventures）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "periodic",
    timing: "期別募集（おおむね2〜3ヶ月ごと）",
    value: "渋谷の無料オフィスを約6ヶ月＋メンタリング",
    eligibility: "創業準備中〜創業期の起業家",
    summary:
      "創業前/創業期に特化したVC mintが運営する無料オフィス支援プログラム。期ごとに選抜チームへ約6ヶ月間オフィスとコミュニティを無償提供する。",
    url: "https://mint-vc.com/",
    tags: ["渋谷", "プレシード"],
  },
  {
    id: "foundx-founders",
    name: "FoundX Founders Program",
    operator: "東京大学 産学協創推進本部",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "periodic",
    timing: "随時/期別（チーム単位で選考）",
    value: "個室オフィス最大9ヶ月・無償・非エクイティ",
    eligibility: "東京大学の卒業生・研究者など関係者",
    summary:
      "東大FoundXが提供する、すでにアイデアを持つチーム向けの最大9ヶ月の無償プログラム。個室と起業家コミュニティを提供。エビデンスに基づく支援が特徴。",
    url: "https://foundx.jp/",
    tags: ["東大", "大学発"],
  },
  {
    id: "foundx-fellows",
    name: "FoundX Fellows Program",
    operator: "東京大学 産学協創推進本部",
    assetTypes: ["community", "mentoring"],
    stages: ["idea"],
    equity: "none",
    timingType: "periodic",
    timing: "期別募集",
    value: "コワーキング席・コミュニティ・無償",
    eligibility: "東京大学関係者でアイデア探索中の個人",
    summary:
      "アイデア探索段階の東大関係者向けプログラム。コワーキングスペースとコミュニティ、リソースへのアクセスを無償で提供する。",
    url: "https://foundx.jp/",
    tags: ["東大", "アイデア探索"],
  },
  {
    id: "todai-ipc-1stround",
    name: "東大IPC 1stRound",
    nameEn: "1stRound",
    operator: "東京大学協創プラットフォーム開発（東大IPC）",
    assetTypes: ["grant-subsidy", "mentoring", "community"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "annual",
    timing: "年1回前後の公募",
    value: "最大1,000万円規模の事業化支援（非返済・非エクイティ）",
    eligibility: "東京大学を含む複数の連携大学の研究者・学生など",
    summary:
      "東大IPCが主導する、株式を取得しない事業化支援プログラム。返済不要の活動資金とハンズオン支援を提供。複数大学が連携。",
    url: "https://www.1stround.jp/",
    tags: ["大学発", "ディープテック"],
  },
  {
    id: "asac",
    name: "青山スタートアップアクセラレーションセンター（ASAC）",
    nameEn: "ASAC",
    operator: "東京都 / 運営事業者",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "periodic",
    timing: "期別募集（年複数期）",
    value: "無料のアクセラ・プログラム＋メンタリング",
    eligibility: "成長志向のスタートアップ",
    summary:
      "東京都の創業・成長支援拠点。約5ヶ月のアクセラレーションプログラムをメンタリング付きで無償提供。デモデイあり。",
    url: "https://asac.tokyo/",
    tags: ["東京都", "公的支援"],
  },
  {
    id: "tokyo-sogyo-station",
    name: "TOKYO創業ステーション",
    operator: "東京都中小企業振興公社",
    assetTypes: ["mentoring", "community", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "always",
    timing: "通年（相談は予約制）",
    value: "無料の事業相談・セミナー・助成金情報",
    eligibility: "都内で創業を目指す個人・事業者",
    summary:
      "担任制プランコンサルタントによる無料の創業相談、仮説検証支援、事業計画ブラッシュアップを提供。創業助成金などへの導線も。",
    url: "https://startup-station.jp/",
    tags: ["東京都", "創業相談"],
  },
  {
    id: "shibuya-qws",
    name: "SHIBUYA QWS",
    nameEn: "QWS",
    operator: "渋谷スクランブルスクエア",
    assetTypes: ["community", "free-office", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "periodic",
    timing: "プロジェクト会員は期別募集",
    value: "会員制の共創施設・プロジェクト支援",
    eligibility: "問いを起点に活動する個人・チーム",
    summary:
      "渋谷スクランブルスクエア内の共創施設。プロジェクト会員制度を通じて活動拠点・コミュニティ・メンタリング・発信機会を提供する。",
    url: "https://shibuya-qws.com/",
    tags: ["渋谷", "共創"],
  },

  // ===== 人材発掘・育成（タレントプログラム） =====
  {
    id: "mitou-it",
    name: "未踏IT人材発掘・育成事業",
    nameEn: "MITOU",
    operator: "情報処理推進機構（IPA）",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    timingType: "annual",
    timing: "年1回公募（おおむね春）",
    value: "開発資金の支援＋トップエンジニアによるPM指導",
    eligibility: "25歳未満などの突出したIT人材（個人/チーム）",
    summary:
      "経産省所管IPAによる、突出したIT人材を発掘・育成する事業。採択者に開発資金とプロジェクトマネージャーによる指導を提供。OB/OGに著名起業家多数。",
    url: "https://www.ipa.go.jp/jinzai/mitou/it/index.html",
    tags: ["IPA", "登竜門"],
  },
  {
    id: "mitou-advanced",
    name: "未踏アドバンスト事業",
    operator: "情報処理推進機構（IPA）",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "annual",
    timing: "年1回公募",
    value: "事業化に向けた費用支援＋伴走",
    eligibility: "技術シーズの事業化を目指す個人・チーム（年齢上限なし）",
    summary:
      "未踏事業の中でも事業化志向に特化したトラック。技術的成果のビジネス化を、費用支援とビジネスメンタリングで後押しする。",
    url: "https://www.ipa.go.jp/jinzai/mitou/advanced/index.html",
    tags: ["IPA", "事業化"],
  },
  {
    id: "mitou-junior",
    name: "未踏ジュニア",
    operator: "一般社団法人 未踏",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    timingType: "annual",
    timing: "年1回公募（春）",
    value: "最大支援金＋メンタリング",
    eligibility: "17歳以下のクリエイター",
    summary:
      "17歳以下の若手クリエイターを対象にした未踏。突出したアイデアと技術力を持つ小中高生に、開発資金とメンターを提供する。",
    url: "https://jr.mitou.org/",
    tags: ["U17", "若手"],
  },
  {
    id: "masason-foundation",
    name: "孫正義育英財団",
    operator: "公益財団法人 孫正義育英財団",
    assetTypes: ["talent-program", "grant-subsidy", "community"],
    stages: ["idea"],
    equity: "none",
    timingType: "annual",
    timing: "年1回前後の募集",
    value: "支援金・施設・ネットワークへのアクセス",
    eligibility: "高い志と異能を持つ若者（25歳以下目安）",
    summary:
      "高い志を持つ若者を支援する財団。財団生には活動支援や拠点（Infinity）、人的ネットワークなどを提供する。",
    url: "https://masason-foundation.org/",
    tags: ["若手", "異能"],
  },

  // ===== クラウド・SaaS クレジット =====
  {
    id: "aws-activate",
    name: "AWS Activate",
    operator: "Amazon Web Services",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（条件を満たせば随時申請）",
    value: "最大 $100,000 のAWSクレジット",
    eligibility: "対象VC/アクセラ等の紹介、または自己応募枠",
    summary:
      "スタートアップ向けにAWS利用クレジット・技術サポート・トレーニングを提供。成長ステージに応じて最大10万ドル相当のクレジットが付与される。",
    url: "https://aws.amazon.com/jp/startups/",
    tags: ["インフラ", "クレジット"],
  },
  {
    id: "ms-startups",
    name: "Microsoft for Startups Founders Hub",
    operator: "Microsoft",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（オンラインで随時申請）",
    value: "最大 $150,000 相当のAzure等クレジット＋OpenAI等の特典",
    eligibility: "ほぼ全ての創業初期スタートアップ（VC不要枠あり）",
    summary:
      "Azureクレジット、開発ツール、OpenAI APIアクセス、メンタリング等をまとめて提供。VCの紹介なしでも申請可能な枠がある。",
    url: "https://www.microsoft.com/startups",
    tags: ["インフラ", "AI"],
  },
  {
    id: "google-cloud-startups",
    name: "Google for Startups Cloud Program",
    operator: "Google Cloud",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（随時申請）",
    value: "最大 $200,000（AI特化枠は更に上限あり）のGCPクレジット",
    eligibility: "創業10年以内・一定の資金調達状況などの条件",
    summary:
      "Google Cloud利用クレジットに加え、技術サポート・トレーニング・スタートアップ専任チームによる支援を提供。AIスタートアップ向けの上乗せ枠もある。",
    url: "https://cloud.google.com/startup",
    tags: ["インフラ", "AI"],
  },
  {
    id: "nvidia-inception",
    name: "NVIDIA Inception",
    operator: "NVIDIA",
    assetTypes: ["cloud-credit", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    timingType: "always",
    timing: "通年（随時申請・無料）",
    value: "ハード/ソフト割引・技術支援・VCネットワーク",
    eligibility: "AI・データサイエンス系スタートアップ",
    summary:
      "AI系スタートアップ向けの無料メンバーシッププログラム。製品割引、技術トレーニング、クラウドクレジット、投資家紹介などを提供。",
    url: "https://www.nvidia.com/en-us/startups/",
    tags: ["AI", "GPU"],
  },
  {
    id: "notion-startups",
    name: "Notion for Startups",
    operator: "Notion",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（パートナー経由で申請）",
    value: "Notion Plus + AI の無料クレジット",
    eligibility: "提携アクセラ/VC等のパートナーに所属",
    summary:
      "対象スタートアップにNotionの有料プラン＋AIを一定期間無料提供。多くのアクセラレーターやVCがパートナーになっている。",
    url: "https://www.notion.com/startups",
    tags: ["SaaS", "生産性"],
  },
  {
    id: "hubspot-startups",
    name: "HubSpot for Startups",
    operator: "HubSpot",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（パートナー経由で申請）",
    value: "初年度最大90%割引などの段階的ディスカウント",
    eligibility: "提携VC/アクセラ等のネットワークに所属",
    summary:
      "CRM・マーケ・セールスツールを大幅割引で提供。提携パートナー経由で申請でき、初年度に高い割引率が適用される。",
    url: "https://www.hubspot.com/startups",
    tags: ["SaaS", "CRM"],
  },

  // ===== アクセラレーター（民間・コーポレート） =====
  {
    id: "onlab",
    name: "Open Network Lab（Onlab）",
    nameEn: "Onlab",
    operator: "デジタルガレージ",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed"],
    equity: "required",
    timingType: "periodic",
    timing: "期別募集（Seed Acceleratorは年複数回）",
    value: "出資＋約3〜4ヶ月の集中支援＋デモデイ",
    eligibility: "シード期のスタートアップ",
    summary:
      "日本の草分け的シードアクセラレーター。少額出資と引き換えに集中メンタリングを行い、デモデイで投資家へ繋ぐ。",
    url: "https://onlab.jp/",
    tags: ["シード", "出資あり"],
  },
  {
    id: "incubate-camp",
    name: "Incubate Camp",
    operator: "インキュベイトファンド",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    timingType: "annual",
    timing: "年1回前後",
    value: "トップVCとの合宿型メンタリング＋投資機会",
    eligibility: "起業直後〜シードの起業家",
    summary:
      "現役VCとペアを組む合宿型アクセラレーション。短期集中で事業をブラッシュアップし、出資につながることも多い。",
    url: "https://incubatefund.com/",
    tags: ["合宿", "VC伴走"],
  },
  {
    id: "plugandplay-japan",
    name: "Plug and Play Japan",
    operator: "Plug and Play Japan",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    timingType: "periodic",
    timing: "バッチ制（年2回前後）",
    value: "大企業との事業共創・無償アクセラ",
    eligibility: "各業界テーマに合致するスタートアップ",
    summary:
      "シリコンバレー発のアクセラ／イノベーションプラットフォーム。テーマ別バッチで大企業とのマッチングやPoC機会を非エクイティで提供。",
    url: "https://japan.plugandplaytechcenter.com/",
    tags: ["オープンイノベーション", "大企業連携"],
  },
  {
    id: "google-accelerator",
    name: "Google for Startups Accelerator",
    operator: "Google",
    assetTypes: ["accelerator", "mentoring", "cloud-credit"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    timingType: "periodic",
    timing: "バッチ制の公募（テーマ別）",
    value: "非エクイティの集中メンタリング＋Google技術支援",
    eligibility: "成長期のテック系スタートアップ",
    summary:
      "Googleが運営する非エクイティのアクセラレーター。Googleのエンジニア・メンターによる技術／事業支援を数ヶ月間提供する。",
    url: "https://startup.google.com/programs/accelerator/",
    tags: ["非エクイティ", "テック"],
  },
  {
    id: "kddi-mugen-labo",
    name: "KDDI ∞ Labo（ムゲンラボ）",
    operator: "KDDI",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    timingType: "periodic",
    timing: "プログラム期別募集",
    value: "大企業連携・メンタリング・事業共創",
    eligibility: "成長志向のスタートアップ",
    summary:
      "KDDIが運営する老舗インキュベーションプログラム。パートナー大企業との連携やメンタリングを通じて事業成長を支援する。",
    url: "https://mugenlabo.kddi.com/",
    tags: ["大企業連携", "コーポレート"],
  },
  {
    id: "tribus",
    name: "TRIBUS",
    operator: "リコー",
    assetTypes: ["accelerator", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "annual",
    timing: "年1回前後の公募",
    value: "リコーのアセット活用・社内外共創",
    eligibility: "社外スタートアップ＋社内起業家",
    summary:
      "リコーが運営する、社内外の起業家が混じり合うアクセラレータープログラム。リコーの技術・販路・顧客基盤を活かした共創を支援。",
    url: "https://tribus.ricoh/",
    tags: ["コーポレート", "共創"],
  },

  // ===== 公的・グローバル展開 =====
  {
    id: "j-startup",
    name: "J-Startup",
    operator: "経済産業省",
    assetTypes: ["community", "overseas", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    timingType: "annual",
    timing: "推薦に基づく選定（不定期）",
    value: "官民の集中支援・海外展開・広報露出",
    eligibility: "推薦により選定された有望スタートアップ",
    summary:
      "経産省主導で有望スタートアップを選定し、官民で集中支援する制度。海外展開支援、規制対応、大企業・自治体連携などの機会を提供。",
    url: "https://www.j-startup.go.jp/",
    tags: ["経産省", "認定"],
  },
  {
    id: "j-starx",
    name: "J-StarX",
    operator: "経済産業省",
    assetTypes: ["overseas", "talent-program", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    timingType: "periodic",
    timing: "コース別に随時公募",
    value: "海外派遣・グローバル起業家育成プログラム",
    eligibility: "起業家・起業を志す学生・企業内人材など",
    summary:
      "起業家等をシリコンバレー等へ派遣する経産省の海外派遣・育成プログラム。コースが多数あり対象や段階に応じて選べる。",
    url: "https://j-starx.jp/",
    tags: ["経産省", "海外派遣"],
  },
  {
    id: "jetro-gsap",
    name: "グローバル・スタートアップ・アクセラレーションプログラム（GSAP）",
    nameEn: "JETRO GSAP",
    operator: "日本貿易振興機構（JETRO）",
    assetTypes: ["overseas", "accelerator", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    timingType: "annual",
    timing: "年1回前後の公募",
    value: "世界トップアクセラによるエクイティフリー支援",
    eligibility: "海外展開を目指すスタートアップ",
    summary:
      "JETROが内閣府等と連携し、世界トップレベルのアクセラレーターによるエクイティフリー型の海外展開支援を提供する。",
    url: "https://www.jetro.go.jp/services/gsap.html",
    tags: ["JETRO", "エクイティフリー"],
  },
  {
    id: "japan-innovation-campus",
    name: "Japan Innovation Campus",
    operator: "経済産業省 / JETRO",
    assetTypes: ["overseas", "community"],
    stages: ["early", "growth"],
    equity: "none",
    timingType: "varies",
    timing: "随時（入居・利用は審査あり）",
    value: "シリコンバレー拠点の活動スペース・現地ネットワーク",
    eligibility: "米国展開を狙うスタートアップ・支援機関",
    summary:
      "米国・シリコンバレーに設けられた日本のスタートアップ支援拠点。現地での活動スペースやネットワーキングの機会を提供する。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["シリコンバレー", "海外拠点"],
  },

  // ===== 補助金・助成金・公的資金 =====
  {
    id: "nedo-nep",
    name: "NEDO 研究開発型スタートアップ支援（NEP / STS / DTSU 等）",
    nameEn: "NEDO",
    operator: "新エネルギー・産業技術総合開発機構（NEDO）",
    assetTypes: ["grant-subsidy", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    timingType: "annual",
    timing: "事業ごとに年1回前後の公募",
    value: "研究開発費の助成＋メンター支援（事業により規模が異なる）",
    eligibility: "研究開発型（ディープテック）スタートアップ",
    summary:
      "NEDOによる研究開発型スタートアップ向け助成の総称。起業前のNEPから、VC連携のSTS、ディープテックのDTSUまで段階別メニューがある。",
    url: "https://www.nedo.go.jp/",
    tags: ["ディープテック", "研究開発"],
  },
  {
    id: "tokyo-sogyo-grant",
    name: "東京都 創業助成事業",
    operator: "東京都中小企業振興公社",
    assetTypes: ["grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    timingType: "periodic",
    timing: "年複数回の募集",
    value: "上限400万円・助成率2/3（年度により変動）",
    eligibility: "都内で創業予定/創業初期かつ一定要件を満たす者",
    summary:
      "都内の創業初期に必要な経費（人件費・賃借料・広告費等）の一部を助成。TOKYO創業ステーション等の支援を受けていることが要件になる場合がある。",
    url: "https://startup-station.jp/m/sogyojosei/",
    tags: ["東京都", "助成金"],
  },
  {
    id: "jfc-startup-loan",
    name: "日本公庫 スタートアップ支援資金 / 新規開業資金",
    operator: "日本政策金融公庫",
    assetTypes: ["funding"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    timingType: "always",
    timing: "通年（随時申込）",
    value: "創業・成長期向けの融資（条件により無担保・無保証）",
    eligibility: "創業予定者・スタートアップ",
    summary:
      "政府系金融機関による創業・スタートアップ向け融資制度。新規開業資金など、創業期でも利用しやすい条件のメニューが用意されている。",
    url: "https://www.jfc.go.jp/n/finance/search/startup.html",
    tags: ["融資", "公的金融"],
  },
  {
    id: "monozukuri-hojokin",
    name: "ものづくり・商業・サービス生産性向上促進補助金",
    operator: "中小企業庁 / 全国中央会",
    assetTypes: ["grant-subsidy"],
    stages: ["early", "growth"],
    equity: "none",
    timingType: "periodic",
    timing: "公募回ごと（年複数回）",
    value: "設備投資・試作開発費の補助（枠により数百万〜数千万円）",
    eligibility: "中小企業・小規模事業者（要件あり）",
    summary:
      "革新的な製品・サービス開発や生産プロセス改善のための設備投資等を補助する代表的な補助金。グローバル枠など複数の申請枠がある。",
    url: "https://portal.monodukuri-hojo.jp/",
    tags: ["補助金", "設備投資"],
  },

  // ===== 横断データベース・情報ハブ =====
  {
    id: "meti-startup-list",
    name: "経済産業省 スタートアップ支援策一覧",
    operator: "経済産業省",
    assetTypes: ["grant-subsidy", "community"],
    stages: ["any"],
    equity: "none",
    timingType: "varies",
    timing: "随時更新（PDF/カオスマップ）",
    value: "補助金・融資・税制など官系施策を一覧化",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "補助金・融資・税制など官系の支援策を網羅的にまとめた公式資料。フェーズ別に使える制度を俯瞰できる。本サイトの官系情報の一次ソース。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["公式", "一次ソース"],
  },
  {
    id: "startup-portal-cas",
    name: "スタートアップ育成ポータルサイト",
    operator: "内閣官房 / 内閣府",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    timingType: "always",
    timing: "通年（情報ポータル）",
    value: "5か年計画ベースの政府支援への入口",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "スタートアップ育成5か年計画に基づく政府の各種取組をまとめた公式ポータル。各省庁の施策や拠点構想への導線を提供する。",
    url: "https://www.cas.go.jp/jp/seisaku/su-portal/index.html",
    tags: ["政府", "ポータル"],
  },
  {
    id: "foundx-resources",
    name: "FoundX Startup Resources",
    operator: "東京大学 FoundX",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    timingType: "always",
    timing: "通年（記事データベース）",
    value: "300本以上の起業ノウハウ・翻訳カリキュラム",
    eligibility: "すべての起業家",
    summary:
      "起業家のためのナレッジまとめサイト。Startup School等の翻訳教材や、資金調達・採用などのノウハウ記事が体系的に整理されている。",
    url: "https://resource.foundx.jp/",
    tags: ["ナレッジ", "学習"],
  },
];
