import type { Asset } from "./types";

// 日本の起業家・スタートアップが使える支援アセットのキュレーション済みデータ。
//
// 募集時期(application)は変動が激しいため、確定日(deadline/opensAt)は裏取りできたものだけを設定し、
// それ以外は周期(window)で「次にいつ頃来るか」を表現しています。
// 金額・条件・締切などの最終情報は必ず各公式サイトでご確認ください。
// データの追加・修正は GitHub への Pull Request を歓迎します。

// 掲載情報の最終確認時点（UIに表示）
export const LAST_CHECKED = "2026年6月";

export const assets: Asset[] = [
  // ===================================================================
  // 無料オフィス・インキュベーション
  // ===================================================================
  {
    id: "flap",
    name: "FLAP",
    operator: "mint（旧 Apricot Ventures）",
    region: "東京（渋谷）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "おおむね2〜3ヶ月ごとに新しい期を募集",
    },
    value: "渋谷の無料オフィスを約6ヶ月＋メンタリング",
    eligibility: "創業準備中〜創業期の起業家",
    summary:
      "創業前/創業期に特化したVC mintが運営する無料オフィス支援プログラム。期ごとに選抜チームへ約6ヶ月間オフィスとコミュニティを無償提供する。",
    url: "https://mint-vc.com/",
    tags: ["渋谷", "プレシード"],
  },
  {
    id: "foundx-founders",
    name: "FoundX Founders Program",
    operator: "東京大学 産学協創推進本部",
    region: "東京（本郷）",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "rolling",
      note: "随時エントリー・選考（チーム単位）",
    },
    value: "個室オフィス最大9ヶ月・無償・非エクイティ",
    eligibility: "東京大学の卒業生・研究者など関係者",
    summary:
      "東大FoundXが提供する、すでにアイデアを持つチーム向けの最大9ヶ月の無償プログラム。個室と起業家コミュニティを提供。エビデンスに基づく支援が特徴。",
    url: "https://foundx.jp/",
    tags: ["東大", "大学発"],
  },
  {
    id: "foundx-fellows",
    name: "FoundX Fellows Program",
    operator: "東京大学 産学協創推進本部",
    region: "東京（本郷）",
    assetTypes: ["community", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: { status: "rolling", note: "随時エントリー・選考" },
    value: "コワーキング席・コミュニティ・無償",
    eligibility: "東京大学関係者でアイデア探索中の個人",
    summary:
      "アイデア探索段階の東大関係者向けプログラム。コワーキングスペースとコミュニティ、リソースへのアクセスを無償で提供する。",
    url: "https://foundx.jp/",
    tags: ["東大", "アイデア探索"],
  },
  {
    id: "todai-ipc-1stround",
    name: "東大IPC 1stRound",
    nameEn: "1stRound",
    operator: "東京大学協創プラットフォーム開発（東大IPC）",
    region: "全国（連携大学）",
    assetTypes: ["grant-subsidy", "mentoring", "community"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 夏〜秋にエントリー）",
    },
    value: "最大1,000万円規模の事業化支援（非返済・非エクイティ）",
    eligibility: "東京大学を含む複数の連携大学の研究者・学生など",
    summary:
      "東大IPCが主導する、株式を取得しない事業化支援プログラム。返済不要の活動資金とハンズオン支援を提供。複数大学が連携。",
    url: "https://www.1stround.jp/",
    tags: ["大学発", "ディープテック"],
  },
  {
    id: "asac",
    name: "青山スタートアップアクセラレーションセンター（ASAC）",
    nameEn: "ASAC",
    operator: "東京都 / 運営事業者",
    region: "東京",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年複数期で募集（1期 約5ヶ月）",
    },
    value: "無料のアクセラ・プログラム＋メンタリング",
    eligibility: "成長志向のスタートアップ",
    summary:
      "東京都の創業・成長支援拠点。約5ヶ月のアクセラレーションプログラムをメンタリング付きで無償提供。デモデイあり。",
    url: "https://asac.tokyo/",
    tags: ["東京都", "公的支援"],
  },
  {
    id: "tokyo-sogyo-station",
    name: "TOKYO創業ステーション",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["mentoring", "community", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: { status: "rolling", note: "通年（相談は予約制）" },
    value: "無料の事業相談・セミナー・助成金情報",
    eligibility: "都内で創業を目指す個人・事業者",
    summary:
      "担任制プランコンサルタントによる無料の創業相談、仮説検証支援、事業計画ブラッシュアップを提供。創業助成金などへの導線も。",
    url: "https://startup-station.jp/",
    tags: ["東京都", "創業相談"],
  },
  {
    id: "startup-hub-tokyo",
    name: "Startup Hub Tokyo",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["community", "mentoring", "free-office"],
    stages: ["idea", "seed"],
    equity: "none",
    application: { status: "rolling", note: "通年（会員登録は無料）" },
    value: "無料の交流スペース・相談・イベント",
    eligibility: "起業に関心のある個人・初期起業家",
    summary:
      "起業を志す人のための無料拠点。コンシェルジュ相談、先輩起業家とのネットワーキング、各種イベントを無償で提供する。",
    url: "https://startup-station.jp/m/startuphubtokyo/",
    tags: ["東京都", "コミュニティ"],
  },
  {
    id: "shibuya-qws",
    name: "SHIBUYA QWS",
    nameEn: "QWS",
    operator: "渋谷スクランブルスクエア",
    region: "東京（渋谷）",
    assetTypes: ["community", "free-office", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "四半期ごとにプロジェクト会員を募集",
    },
    value: "会員制の共創施設・プロジェクト支援",
    eligibility: "問いを起点に活動する個人・チーム",
    summary:
      "渋谷スクランブルスクエア内の共創施設。プロジェクト会員制度を通じて活動拠点・コミュニティ・メンタリング・発信機会を提供する。",
    url: "https://shibuya-qws.com/",
    tags: ["渋谷", "共創"],
  },
  {
    id: "fukuoka-growth-next",
    name: "Fukuoka Growth Next（FGN）",
    nameEn: "FGN",
    operator: "福岡市 ほか",
    region: "福岡",
    assetTypes: ["free-office", "community", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "入居・会員は随時審査" },
    value: "官民共働の拠点・低コストの入居・支援",
    eligibility: "福岡を拠点とするスタートアップ",
    summary:
      "旧大名小学校を活用した福岡市の官民共働スタートアップ支援施設。低コストの入居、メンタリング、コミュニティ、イベントを提供する。",
    url: "https://growth-next.com/",
    tags: ["福岡", "地方拠点"],
  },
  {
    id: "osaka-innovation-hub",
    name: "Osaka Innovation Hub（OIH）",
    nameEn: "OIH",
    operator: "大阪市 / 大阪産業局",
    region: "大阪",
    assetTypes: ["community", "mentoring", "overseas"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: {
      status: "rolling",
      note: "通年（イベント・プログラムは随時）",
    },
    value: "無料の交流拠点・ピッチ・海外連携",
    eligibility: "起業家・イノベーター（誰でも）",
    summary:
      "大阪市が運営するイノベーション創出拠点。グランフロント大阪を拠点に、年間多数のイベント、メンタリング、海外アクセラ連携などを提供。",
    url: "https://www.innovation-osaka.jp/",
    tags: ["大阪", "地方拠点"],
  },
  {
    id: "yoxo-yokohama",
    name: "YOXO（横浜スタートアップ支援）",
    nameEn: "YOXO",
    operator: "横浜市 / 横浜未来機構",
    region: "神奈川（横浜）",
    assetTypes: ["accelerator", "community", "free-office"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "アクセラは年次公募（YOXO ACCELERATOR）",
    },
    value: "無料アクセラ・交流拠点（YOXO BOX）",
    eligibility: "横浜での成長を目指すスタートアップ",
    summary:
      "横浜市のスタートアップ成長支援ブランド。交流拠点YOXO BOXや、専門家伴走型のYOXO ACCELERATORなどを通じて事業成長を支援する。",
    url: "https://yoxo-yokohama.com/",
    tags: ["横浜", "地方拠点"],
  },

  // ===================================================================
  // 人材発掘・育成（タレントプログラム）
  // ===================================================================
  {
    id: "mitou-it",
    name: "未踏IT人材発掘・育成事業",
    nameEn: "MITOU",
    operator: "情報処理推進機構（IPA）",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年11月エントリー開始〜翌3月締切",
      note: "2026年度は2026/3/12で公募終了。次は2026年度後半に告知見込み",
    },
    value: "開発資金の支援＋トップエンジニアによるPM指導",
    eligibility: "25歳未満などの突出したIT人材（個人/チーム）",
    summary:
      "経産省所管IPAによる、突出したIT人材を発掘・育成する事業。採択者に開発資金とプロジェクトマネージャーによる指導を提供。OB/OGに著名起業家多数。",
    url: "https://www.ipa.go.jp/jinzai/mitou/it/index.html",
    tags: ["IPA", "登竜門"],
  },
  {
    id: "mitou-advanced",
    name: "未踏アドバンスト事業",
    operator: "情報処理推進機構（IPA）",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "上期・下期の年2回（おおむね12〜3月にエントリー）",
    },
    value: "事業化に向けた費用支援＋伴走",
    eligibility: "技術シーズの事業化を目指す個人・チーム（年齢上限なし）",
    summary:
      "未踏事業の中でも事業化志向に特化したトラック。技術的成果のビジネス化を、費用支援とビジネスメンタリングで後押しする。",
    url: "https://www.ipa.go.jp/jinzai/mitou/advanced/index.html",
    tags: ["IPA", "事業化"],
  },
  {
    id: "mitou-junior",
    name: "未踏ジュニア",
    operator: "一般社団法人 未踏",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "mentoring"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年春（おおむね3〜4月）に公募",
    },
    value: "支援金＋メンタリング",
    eligibility: "17歳以下のクリエイター",
    summary:
      "17歳以下の若手クリエイターを対象にした未踏。突出したアイデアと技術力を持つ小中高生に、開発資金とメンターを提供する。",
    url: "https://jr.mitou.org/",
    tags: ["U17", "若手"],
  },
  {
    id: "masason-foundation",
    name: "孫正義育英財団",
    operator: "公益財団法人 孫正義育英財団",
    region: "全国",
    assetTypes: ["talent-program", "grant-subsidy", "community"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年募集（時期は年により変動）",
    },
    value: "支援金・施設（Infinity）・ネットワーク",
    eligibility: "高い志と異能を持つ若者（25歳以下目安）",
    summary:
      "高い志を持つ若者を支援する財団。財団生には活動支援や拠点（Infinity）、人的ネットワークなどを提供する。",
    url: "https://masason-foundation.org/",
    tags: ["若手", "異能"],
  },
  {
    id: "tokyo-startup-gateway",
    name: "TOKYO STARTUP GATEWAY（TSG）",
    nameEn: "TSG",
    operator: "東京都 / NPO ETIC.",
    region: "東京",
    assetTypes: ["talent-program", "mentoring", "community"],
    stages: ["idea"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年 初夏〜夏に公募（ビジネスコンテスト型）",
    },
    value: "無料の起業家育成プログラム＋賞金・伴走",
    eligibility: "都内在住・在勤などの起業を志す個人",
    summary:
      "東京都の起業家発掘・育成プログラム。400字の応募から始まり、半年間のメンタリングを経て事業化を目指す登竜門型コンテスト。参加無料。",
    url: "https://tokyo-startup.jp/",
    tags: ["東京都", "ビジコン"],
  },

  // ===================================================================
  // クラウド・SaaS クレジット
  // ===================================================================
  {
    id: "aws-activate",
    name: "AWS Activate",
    operator: "Amazon Web Services",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（条件を満たせば随時申請）" },
    value: "最大 $100,000 のAWSクレジット",
    eligibility: "対象VC/アクセラ等の紹介、または自己応募枠",
    summary:
      "スタートアップ向けにAWS利用クレジット・技術サポート・トレーニングを提供。成長ステージに応じて最大10万ドル相当のクレジットが付与される。",
    url: "https://aws.amazon.com/jp/startups/",
    tags: ["インフラ", "クレジット"],
  },
  {
    id: "ms-startups",
    name: "Microsoft for Startups Founders Hub",
    operator: "Microsoft",
    region: "全国",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（オンラインで随時申請）" },
    value: "最大 $150,000 相当のAzure等クレジット＋OpenAI等の特典",
    eligibility: "ほぼ全ての創業初期スタートアップ（VC不要枠あり）",
    summary:
      "Azureクレジット、開発ツール、OpenAI APIアクセス、メンタリング等をまとめて提供。VCの紹介なしでも申請可能な枠がある。",
    url: "https://www.microsoft.com/startups",
    tags: ["インフラ", "AI"],
  },
  {
    id: "google-cloud-startups",
    name: "Google for Startups Cloud Program",
    operator: "Google Cloud",
    region: "全国",
    assetTypes: ["cloud-credit", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申請）" },
    value: "最大 $200,000（AI特化枠は更に上限あり）のGCPクレジット",
    eligibility: "創業10年以内・一定の資金調達状況などの条件",
    summary:
      "Google Cloud利用クレジットに加え、技術サポート・トレーニング・スタートアップ専任チームによる支援を提供。AIスタートアップ向けの上乗せ枠もある。",
    url: "https://cloud.google.com/startup",
    tags: ["インフラ", "AI"],
  },
  {
    id: "nvidia-inception",
    name: "NVIDIA Inception",
    operator: "NVIDIA",
    region: "全国",
    assetTypes: ["cloud-credit", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申請・無料）" },
    value: "ハード/ソフト割引・技術支援・VCネットワーク",
    eligibility: "AI・データサイエンス系スタートアップ",
    summary:
      "AI系スタートアップ向けの無料メンバーシッププログラム。製品割引、技術トレーニング、クラウドクレジット、投資家紹介などを提供。",
    url: "https://www.nvidia.com/en-us/startups/",
    tags: ["AI", "GPU"],
  },
  {
    id: "notion-startups",
    name: "Notion for Startups",
    operator: "Notion",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（パートナー経由で申請）" },
    value: "Notion Plus + AI の無料クレジット",
    eligibility: "提携アクセラ/VC等のパートナーに所属",
    summary:
      "対象スタートアップにNotionの有料プラン＋AIを一定期間無料提供。多くのアクセラレーターやVCがパートナーになっている。",
    url: "https://www.notion.com/startups",
    tags: ["SaaS", "生産性"],
  },
  {
    id: "hubspot-startups",
    name: "HubSpot for Startups",
    operator: "HubSpot",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（パートナー経由で申請）" },
    value: "初年度最大90%割引などの段階的ディスカウント",
    eligibility: "提携VC/アクセラ等のネットワークに所属",
    summary:
      "CRM・マーケ・セールスツールを大幅割引で提供。提携パートナー経由で申請でき、初年度に高い割引率が適用される。",
    url: "https://www.hubspot.com/startups",
    tags: ["SaaS", "CRM"],
  },
  {
    id: "cloudflare-startups",
    name: "Cloudflare for Startups",
    operator: "Cloudflare",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（提携パートナー経由）" },
    value: "Cloudflare各種プランのクレジット",
    eligibility: "提携VC/アクセラ等のパートナーに所属",
    summary:
      "CDN・セキュリティ・エッジ実行環境などCloudflare製品のクレジットを提供。提携パートナーのスタートアップが対象。",
    url: "https://www.cloudflare.com/forstartups/",
    tags: ["インフラ", "エッジ"],
  },
  {
    id: "mongodb-startups",
    name: "MongoDB for Startups",
    operator: "MongoDB",
    region: "全国",
    assetTypes: ["cloud-credit"],
    stages: ["seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（オンライン申請）" },
    value: "Atlasクレジット＋技術アドバイザー支援",
    eligibility: "創業初期のスタートアップ",
    summary:
      "マネージドDB「Atlas」の利用クレジットに加え、技術アドバイザーやパートナー特典を提供する。",
    url: "https://www.mongodb.com/startups",
    tags: ["インフラ", "DB"],
  },

  // ===================================================================
  // アクセラレーター（民間・コーポレート）
  // ===================================================================
  {
    id: "onlab",
    name: "Open Network Lab（Onlab）",
    nameEn: "Onlab",
    operator: "デジタルガレージ",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "Seed Accelerator は年複数回のバッチ",
    },
    value: "出資＋約3〜4ヶ月の集中支援＋デモデイ",
    eligibility: "シード期のスタートアップ",
    summary:
      "日本の草分け的シードアクセラレーター。少額出資と引き換えに集中メンタリングを行い、デモデイで投資家へ繋ぐ。",
    url: "https://onlab.jp/",
    tags: ["シード", "出資あり"],
  },
  {
    id: "incubate-camp",
    name: "Incubate Camp",
    operator: "インキュベイトファンド",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "毎年開催（おおむね夏〜秋）",
    },
    value: "トップVCとの合宿型メンタリング＋投資機会",
    eligibility: "起業直後〜シードの起業家",
    summary:
      "現役VCとペアを組む合宿型アクセラレーション。短期集中で事業をブラッシュアップし、出資につながることも多い。",
    url: "https://incubatefund.com/",
    tags: ["合宿", "VC伴走"],
  },
  {
    id: "01booster",
    name: "01Booster Accelerator",
    nameEn: "01Booster",
    operator: "ゼロワンブースター",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "community"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "プログラム/テーマごとに公募",
    },
    value: "大企業連携の事業共創・メンタリング",
    eligibility: "成長志向のスタートアップ・新規事業家",
    summary:
      "国内最大級のアクセラレーター運営会社。大企業や自治体と連携した数多くのアクセラレーションプログラムを通じ、事業共創とメンタリングを提供する。",
    url: "https://01booster.co.jp/",
    tags: ["オープンイノベーション", "事業共創"],
  },
  {
    id: "samurai-incubate",
    name: "Samurai Incubate",
    operator: "サムライインキュベート",
    region: "全国",
    assetTypes: ["equity-investment", "accelerator", "mentoring"],
    stages: ["seed"],
    equity: "required",
    application: { status: "rolling", note: "随時、投資・支援を検討" },
    value: "シード出資＋ハンズオン支援",
    eligibility: "シード期スタートアップ",
    summary:
      "シード期に特化した投資・育成会社。出資とともに採用・事業開発などのハンズオン支援を行い、大企業連携プログラムも運営する。",
    url: "https://www.samurai-incubate.asia/",
    tags: ["シード", "出資あり"],
  },
  {
    id: "antler-japan",
    name: "Antler Japan",
    operator: "Antler",
    region: "全国",
    assetTypes: ["accelerator", "equity-investment", "community"],
    stages: ["idea", "seed"],
    equity: "required",
    application: {
      status: "recurring",
      window: "年複数回のコーホート（共同創業者探索から）",
    },
    value: "共同創業者マッチング＋初期出資",
    eligibility: "起業を志す個人（チーム未結成でも可）",
    summary:
      "グローバル展開する「ゼロからの起業」支援プラットフォーム。共同創業者探索のコーホートから始まり、有望チームへ初期出資を行う。",
    url: "https://www.antler.co/location/japan",
    tags: ["共同創業", "グローバル"],
  },
  {
    id: "deepcore",
    name: "DEEPCORE（KERNEL）",
    operator: "ディープコア",
    region: "全国",
    assetTypes: ["equity-investment", "community", "free-office"],
    stages: ["seed", "early"],
    equity: "required",
    application: {
      status: "rolling",
      note: "随時、投資・インキュベーションを検討",
    },
    value: "AI特化の出資＋コミュニティKERNEL＋GPU環境",
    eligibility: "AI領域のスタートアップ・研究者",
    summary:
      "AIに特化したインキュベーター。出資に加え、コミュニティ「KERNEL」やGPU計算環境、研究者ネットワークへのアクセスを提供する。",
    url: "https://deepcore.jp/",
    tags: ["AI", "出資あり"],
  },
  {
    id: "beyond-next-brave",
    name: "Beyond Next Ventures「BRAVE」",
    nameEn: "BRAVE",
    operator: "Beyond Next Ventures",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "equity-investment"],
    stages: ["idea", "seed"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "毎年シーズン開催（アクセラレーション公募）",
    },
    value: "アカデミア発の事業化伴走＋投資機会",
    eligibility: "研究シーズを持つ研究者・起業家",
    summary:
      "技術系・アカデミア発スタートアップに特化したアクセラレーター。研究シーズの事業化を、メンタリングと投資検討を通じて支援する。",
    url: "https://beyondnextventures.com/",
    tags: ["ディープテック", "アカデミア"],
  },
  {
    id: "plugandplay-japan",
    name: "Plug and Play Japan",
    operator: "Plug and Play Japan",
    region: "全国",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "テーマ別バッチ（年2回前後）",
    },
    value: "大企業との事業共創・非エクイティのアクセラ",
    eligibility: "各業界テーマに合致するスタートアップ",
    summary:
      "シリコンバレー発のアクセラ／イノベーションプラットフォーム。テーマ別バッチで大企業とのマッチングやPoC機会を非エクイティで提供。",
    url: "https://japan.plugandplaytechcenter.com/",
    tags: ["オープンイノベーション", "大企業連携"],
  },
  {
    id: "google-accelerator",
    name: "Google for Startups Accelerator",
    operator: "Google",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "cloud-credit"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "テーマ別バッチで随時公募",
    },
    value: "非エクイティの集中メンタリング＋Google技術支援",
    eligibility: "成長期のテック系スタートアップ",
    summary:
      "Googleが運営する非エクイティのアクセラレーター。Googleのエンジニア・メンターによる技術／事業支援を数ヶ月間提供する。",
    url: "https://startup.google.com/programs/accelerator/",
    tags: ["非エクイティ", "テック"],
  },
  {
    id: "kddi-mugen-labo",
    name: "KDDI ∞ Labo（ムゲンラボ）",
    operator: "KDDI",
    region: "全国",
    assetTypes: ["accelerator", "community", "mentoring"],
    stages: ["seed", "early"],
    equity: "optional",
    application: {
      status: "recurring",
      window: "プログラム期ごとに募集",
    },
    value: "大企業連携・メンタリング・事業共創",
    eligibility: "成長志向のスタートアップ",
    summary:
      "KDDIが運営する老舗インキュベーションプログラム。パートナー大企業との連携やメンタリングを通じて事業成長を支援する。",
    url: "https://mugenlabo.kddi.com/",
    tags: ["大企業連携", "コーポレート"],
  },
  {
    id: "tribus",
    name: "TRIBUS",
    operator: "リコー",
    region: "全国",
    assetTypes: ["accelerator", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 夏頃）",
    },
    value: "リコーのアセット活用・社内外共創",
    eligibility: "社外スタートアップ＋社内起業家",
    summary:
      "リコーが運営する、社内外の起業家が混じり合うアクセラレータープログラム。リコーの技術・販路・顧客基盤を活かした共創を支援。",
    url: "https://tribus.ricoh/",
    tags: ["コーポレート", "共創"],
  },

  // ===================================================================
  // ピッチ・登壇機会
  // ===================================================================
  {
    id: "ivs-launchpad",
    name: "IVS LAUNCHPAD",
    operator: "IVS",
    region: "全国",
    assetTypes: ["community", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年（IVS開催に合わせて公募）",
    },
    value: "国内最大級のピッチ登壇・露出機会",
    eligibility: "選考を通過したスタートアップ",
    summary:
      "国内有数のスタートアップカンファレンスIVSのピッチコンテスト。登壇により投資家・事業会社への露出と認知獲得の機会を得られる。",
    url: "https://www.ivs.events/",
    tags: ["ピッチ", "露出"],
  },
  {
    id: "icc-catapult",
    name: "ICC スタートアップ・カタパルト",
    operator: "ICCパートナーズ",
    region: "全国",
    assetTypes: ["community", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "年2回（ICCサミットに合わせて公募）",
    },
    value: "経営者コミュニティでのピッチ登壇機会",
    eligibility: "選考を通過したスタートアップ",
    summary:
      "ICCサミットで開催される登壇型ピッチ。質の高い経営者コミュニティの前でのプレゼン機会と、強いネットワークへのアクセスを提供する。",
    url: "https://www.industry-co-creation.com/",
    tags: ["ピッチ", "コミュニティ"],
  },
  {
    id: "tech-planter",
    name: "TECH PLANTER",
    operator: "リバネス",
    region: "全国",
    assetTypes: ["community", "mentoring", "grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年シーズン開催（分野別の研究シーズコンテスト）",
    },
    value: "研究シーズの事業化伴走＋パートナー連携",
    eligibility: "研究者・ディープテック起業家",
    summary:
      "リバネスが運営する研究シーズの事業化プラットフォーム。分野別コンテストと伴走支援を通じて、ディープテックの種を事業へと育てる。",
    url: "https://techplanter.com/",
    tags: ["ディープテック", "研究シーズ"],
  },

  // ===================================================================
  // 公的・グローバル展開
  // ===================================================================
  {
    id: "j-startup",
    name: "J-Startup",
    operator: "経済産業省",
    region: "全国",
    assetTypes: ["community", "overseas", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "closed",
      note: "一般公募ではなく推薦に基づく選定（不定期）",
    },
    value: "官民の集中支援・海外展開・広報露出",
    eligibility: "推薦により選定された有望スタートアップ",
    summary:
      "経産省主導で有望スタートアップを選定し、官民で集中支援する制度。海外展開支援、規制対応、大企業・自治体連携などの機会を提供。",
    url: "https://www.j-startup.go.jp/",
    tags: ["経産省", "認定"],
  },
  {
    id: "j-starx",
    name: "J-StarX",
    operator: "経済産業省",
    region: "全国 → 海外",
    assetTypes: ["overseas", "talent-program", "mentoring"],
    stages: ["seed", "early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "コース別に随時公募（年間を通じて多数）",
    },
    value: "海外派遣・グローバル起業家育成プログラム",
    eligibility: "起業家・起業を志す学生・企業内人材など",
    summary:
      "起業家等をシリコンバレー等へ派遣する経産省の海外派遣・育成プログラム。コースが多数あり対象や段階に応じて選べる。",
    url: "https://j-starx.jp/",
    tags: ["経産省", "海外派遣"],
  },
  {
    id: "jetro-gsap",
    name: "グローバル・スタートアップ・アクセラレーションプログラム（GSAP）",
    nameEn: "JETRO GSAP",
    operator: "日本貿易振興機構（JETRO）",
    region: "全国 → 海外",
    assetTypes: ["overseas", "accelerator", "mentoring"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（例年 春〜初夏）",
    },
    value: "世界トップアクセラによるエクイティフリー支援",
    eligibility: "海外展開を目指すスタートアップ",
    summary:
      "JETROが内閣府等と連携し、世界トップレベルのアクセラレーターによるエクイティフリー型の海外展開支援を提供する。",
    url: "https://www.jetro.go.jp/services/gsap.html",
    tags: ["JETRO", "エクイティフリー"],
  },
  {
    id: "japan-innovation-campus",
    name: "Japan Innovation Campus",
    operator: "経済産業省 / JETRO",
    region: "米国（シリコンバレー）",
    assetTypes: ["overseas", "community"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "rolling",
      note: "利用・入居は審査制（随時）",
    },
    value: "シリコンバレー拠点の活動スペース・現地ネットワーク",
    eligibility: "米国展開を狙うスタートアップ・支援機関",
    summary:
      "米国・シリコンバレーに設けられた日本のスタートアップ支援拠点。現地での活動スペースやネットワーキングの機会を提供する。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["シリコンバレー", "海外拠点"],
  },

  // ===================================================================
  // 補助金・助成金・公的資金
  // ===================================================================
  {
    id: "nedo-nep",
    name: "NEDO 研究開発型スタートアップ支援（NEP / STS / DTSU 等）",
    nameEn: "NEDO",
    operator: "新エネルギー・産業技術総合開発機構（NEDO）",
    region: "全国",
    assetTypes: ["grant-subsidy", "mentoring"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年1〜4月に公募（コース別）",
      note: "2026年度は開拓2/24・躍進4/17で締切（終了）。次年度は2027年初頭見込み",
    },
    value: "研究開発費の助成＋メンター支援（事業により規模が異なる）",
    eligibility: "研究開発型（ディープテック）スタートアップ",
    summary:
      "NEDOによる研究開発型スタートアップ向け助成の総称。起業前のNEPから、VC連携のSTS、ディープテックのDTSUまで段階別メニューがある。",
    url: "https://www.nedo.go.jp/",
    tags: ["ディープテック", "研究開発"],
  },
  {
    id: "tokyo-sogyo-grant",
    name: "東京都 創業助成事業",
    operator: "東京都中小企業振興公社",
    region: "東京",
    assetTypes: ["grant-subsidy"],
    stages: ["idea", "seed"],
    equity: "none",
    application: {
      status: "upcoming",
      opensAt: "2026-09-29",
      deadline: "2026-10-08",
      window: "毎年 4月・10月頃の年2回",
      note: "第2回（令和8年度）の申請受付。第1回は4/16で終了",
    },
    value: "上限400万円・助成率2/3（年度により変動）",
    eligibility: "都内で創業予定/創業初期かつ一定要件を満たす者",
    summary:
      "都内の創業初期に必要な経費（人件費・賃借料・広告費等）の一部を助成。TOKYO創業ステーション等の支援を受けていることが要件になる場合がある。",
    url: "https://startup-station.jp/m/sogyojosei/",
    tags: ["東京都", "助成金"],
  },
  {
    id: "smrj-fastar",
    name: "中小機構 FASTAR",
    nameEn: "FASTAR",
    operator: "中小企業基盤整備機構（中小機構）",
    region: "全国",
    assetTypes: ["accelerator", "mentoring", "grant-subsidy"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "毎年公募（ギア期ごと）",
    },
    value: "公的アクセラによる非エクイティの集中伴走",
    eligibility: "成長を目指すスタートアップ・中小企業",
    summary:
      "中小機構が運営する非エクイティのアクセラレーション。専属サポーターによる事業計画づくりや資金調達準備の集中伴走を無償で提供する。",
    url: "https://fastar.smrj.go.jp/",
    tags: ["公的支援", "非エクイティ"],
  },
  {
    id: "sbir",
    name: "SBIR制度（中小企業技術革新制度）",
    nameEn: "SBIR",
    operator: "内閣府 / 各省庁",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["seed", "early"],
    equity: "none",
    application: {
      status: "recurring",
      window: "各省庁の指定補助金として年次公募",
    },
    value: "研究開発補助＋随意契約等の出口支援",
    eligibility: "研究開発に取り組むスタートアップ・中小企業",
    summary:
      "国の研究開発予算をスタートアップ等に重点配分する制度。各省庁の指定補助金を通じた研究開発フェーズ別の支援と、公共調達への接続を図る。",
    url: "https://www8.cao.go.jp/cstp/sbir/index.html",
    tags: ["研究開発", "公共調達"],
  },
  {
    id: "jfc-startup-loan",
    name: "日本公庫 スタートアップ支援資金 / 新規開業資金",
    operator: "日本政策金融公庫",
    region: "全国",
    assetTypes: ["funding"],
    stages: ["idea", "seed", "early"],
    equity: "none",
    application: { status: "rolling", note: "通年（随時申込）" },
    value: "創業・成長期向けの融資（条件により無担保・無保証）",
    eligibility: "創業予定者・スタートアップ",
    summary:
      "政府系金融機関による創業・スタートアップ向け融資制度。新規開業資金など、創業期でも利用しやすい条件のメニューが用意されている。",
    url: "https://www.jfc.go.jp/n/finance/search/startup.html",
    tags: ["融資", "公的金融"],
  },
  {
    id: "monozukuri-hojokin",
    name: "ものづくり・商業・サービス生産性向上促進補助金",
    operator: "中小企業庁 / 全国中央会",
    region: "全国",
    assetTypes: ["grant-subsidy"],
    stages: ["early", "growth"],
    equity: "none",
    application: {
      status: "recurring",
      window: "公募回ごと（年数回）",
      note: "2026年度以降は新事業進出補助金との統合・再編が予定",
    },
    value: "設備投資・試作開発費の補助（枠により数百万〜数千万円）",
    eligibility: "中小企業・小規模事業者（要件あり）",
    summary:
      "革新的な製品・サービス開発や生産プロセス改善のための設備投資等を補助する代表的な補助金。グローバル枠など複数の申請枠がある。",
    url: "https://portal.monodukuri-hojo.jp/",
    tags: ["補助金", "設備投資"],
  },

  // ===================================================================
  // 横断データベース・情報ハブ
  // ===================================================================
  {
    id: "meti-startup-list",
    name: "経済産業省 スタートアップ支援策一覧",
    operator: "経済産業省",
    region: "全国",
    assetTypes: ["grant-subsidy", "community"],
    stages: ["any"],
    equity: "none",
    application: {
      status: "rolling",
      note: "情報資料（随時更新・カオスマップ）",
    },
    value: "補助金・融資・税制など官系施策を一覧化",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "補助金・融資・税制など官系の支援策を網羅的にまとめた公式資料。フェーズ別に使える制度を俯瞰できる。本サイトの官系情報の一次ソース。",
    url: "https://www.meti.go.jp/policy/newbusiness/index.html",
    tags: ["公式", "一次ソース"],
  },
  {
    id: "startup-portal-cas",
    name: "スタートアップ育成ポータルサイト",
    operator: "内閣官房 / 内閣府",
    region: "全国",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "情報ポータル（通年）" },
    value: "5か年計画ベースの政府支援への入口",
    eligibility: "すべての起業家・スタートアップ",
    summary:
      "スタートアップ育成5か年計画に基づく政府の各種取組をまとめた公式ポータル。各省庁の施策や拠点構想への導線を提供する。",
    url: "https://www.cas.go.jp/jp/seisaku/su-portal/index.html",
    tags: ["政府", "ポータル"],
  },
  {
    id: "foundx-resources",
    name: "FoundX Startup Resources",
    operator: "東京大学 FoundX",
    region: "全国",
    assetTypes: ["community"],
    stages: ["any"],
    equity: "none",
    application: { status: "rolling", note: "ナレッジDB（通年・無償）" },
    value: "300本以上の起業ノウハウ・翻訳カリキュラム",
    eligibility: "すべての起業家",
    summary:
      "起業家のためのナレッジまとめサイト。Startup School等の翻訳教材や、資金調達・採用などのノウハウ記事が体系的に整理されている。",
    url: "https://resource.foundx.jp/",
    tags: ["ナレッジ", "学習"],
  },
];
